// Localizations_Language_Identifier
import 'package:smeapp/Helper/AppSetting.dart';

enum Localizations_Language_Identifier{
  Language_TC,
  Language_Eng ,
}

extension Language on Localizations_Language_Identifier{

  String get id{
    switch(this){
      case Localizations_Language_Identifier.Language_TC:
        return "繁體中文";
        break;
      case Localizations_Language_Identifier.Language_Eng:
        return "English";
        break;
    }
  }

}

// Localizations_Text_Identifier
enum Localizations_Text_Identifier{
  appTitle,
  ExitAppWarningText,
  loginIdHintText,
  loginPwHintText,
  InvitationHintText,
  AcceptUserPolicyHintText,
  AcceptPrivacyPolicyHintText,
  UnAcceptedPolicyText,
  loginButtonText,
  loginRememberAccountText,
  logoutButtonText,
  HomePageText,
  EmailHintText,
  FirstNameHintText,
  LastNameHintText,
  NickNameHintText,
  GenderHintText,
  Signup_UserPolicyTitle,
  Signup_PrivacyPolicyTitle,
  Signup_EmailManual,
  Signup_IDManual,
  Signup_PWManual,
  Signup_InvitationCodeManual,
  Signup_Confirmation_Title,
  Signup_Confirmation_Desc,
  Signup_Confirmation_Confirm,
  Signup_Confirmation_Cancel,
  signupButtonText,
  ProfilesLabelText,
  Register_ProfilesLabelText,
  AccountLabelText,
  settingButtonText,
  languageButtonText,
  autoLoginText,
  NotificationPermission,
  NotificationPermission_Description,
  NotificationPermission_Title,
  NotificationPermission_Confirm,
  NotificationPermission_Recommend,
  NotificationPermission_RecommendDescription,
  NotificationPermission_Recommend_ToSetting,
  fontSize_Small,
  fontSize_Middle,
  fontSize_Large,
  fontSize_ExtraLarge,
  fontSizeSelectorDefaultDesc,
  fontSizeSelectorText,
  fontSizeSelector_Warning,
  loadingText,
  SelectText,
  Text_male,
  Text_Female,
  Text_Other,
  Register_Success,
  Register_Error_TopLine,
  Register_Error_EmailExists,
  Register_Error_UserExists,
  Register_Error_INVCodeError,
  Register_Error_INVCodeLimited,
  Register_Error_IPLimited,
  Register_Error_NotFillAll_TopLine,
  Login_Success,
  Login_Error_TopLine,
  Login_Error_IncorrectUserName,
  Login_Error_IncorrectPassword,
  Login_Error_Unverified_Email,
  Login_Error_NotFillAll_TopLine,
  Logout_Error_TopLine,
  Logout_Success,
  Connection_Error,
  Connection_Error_FormatException,
  Connection_Error_HandshakeException,
  Connection_Timeout,
  Connection_TokenChecking,
  Connection_TokenError,
  Connection_ReloginBtn,
  Verifier_Loading,
  Verifier_Error_IncorrectAppCode_Android,
  Verifier_Error_IncorrectAppCode_IOS,
  Verifier_Error_IncorrectAppVersion_Android,
  Verifier_Error_IncorrectAppVersion_IOS,
  Tips_Warning,
  Tips_Success,
  Tips_Error,
  Confirm,
  Cancel,
  Retry,
  GoToAppStore_IOS,
  GoToAppStore_Android,
  Exit,
  Exit_iOS_Warning,
  Close,
  LoadingTitle,
  Preview,
  Internet_ConnectionTips,
  Permission_Titleforasking,
  Permission_askforStorage,
  Permission_askforNotification,
  Permission_isPermanentlyDenied,
  Permission_Endingforasking,
  Permission_NotificationDenied,
  GoToApplicationSetting,
  Profiles_Error_LoadingFailed,
  Material_NewLearningMaterial,
  Material_TitleLabelText,
  Material_DescLabelText,
  Material_RequiredTimeLabelText,
  Material_StartTimeLabelText,
  Material_StartDateLabelText,
  Material_EndTimeLabelText,
  Material_EndDateLabelText,
  Material_StartDateTimeLabelText,
  Material_EndDateTimeLabelText,
  Material_DateTimeSelection_HintText,
  Material_UploadAttachment,
  Material_FilesSelecter_AddFiles,
  Material_FilesSelecter_Manual,
  Material_FilesSelecter_SizeWarningTitle,
  Material_FilesSelecter_OverLimitOfSelection,
  Material_FilesSelecter_LoadingFilesList,
  Material_FilesSelecter_FilesRemaining,
  Material_FilesSelecter_ServerAttachment,
  Material_FilesSelecter_ServerAttachment_WillKeep,
  Material_FilesSelecter_ServerAttachment_WillDelete,
  Material_FilesSelecter_ServerAttachment_Keep,
  Material_FilesSelecter_ServerAttachment_Delete,
  Material_FilesSelecter_NewAttachment,
  Material_FilesSelecter_NewAttachment_WillAdd,
  Material_UploadLinks,
  Material_FilesSelecter_AddLinks,
  Material_FilesSelecter_AddLinksManual,
  Material_FilesSelecter_LoadingLinksList,
  Material_FilesSelecter_ServerLinks,
  Material_FilesSelecter_ServerLinks_WillKeep,
  Material_FilesSelecter_ServerLinks_WillDelete,
  Material_FilesSelecter_ServerLinks_Keep,
  Material_FilesSelecter_ServerLinks_Delete,
  Material_FilesSelecter_NewLinks,
  Material_FilesSelecter_NewLinks_WillAdd,
  Material_FilesSelecter_NewLinks_Dialog_NameLabel,
  Material_FilesSelecter_NewLinks_Dialog_URLLabel,
  Material_UploadFormNotAllFill,
  Material_UploadFormReset,
  Material_UploadFormReset_Warning,
  Material_InsertLinkSuccess,
  DateTimeSettingError_EndBeforeStart,
  DateTimeSettingError_StartAfterEnd,
  Material_Preview_Title,
  Material_Preview_EditDetails,
  Material_Preview_EditAttachment,
  Material_Preview_EditLinks,
  Material_Preview_NoAnyAttachment,
  ConfirmUpload,
  ConfirmAdd,
  Material_FilesUploader_Title,
  Material_FilesUploader_Uploading,
  Material_FilesUploader_WaitforUpload,
  Material_FilesUploader_Success,
  Material_FilesUploader_Fail,
  Material_FilesUploader_Retry,
  Material_FilesUploader_FinishSubmission,
  Material_FilesUploader_Inserting,
  Material_FilesUploader_InsertSuccess,
  Material_FilesUploader_InsertFail,
  Material_FilesUploader_LoadingServerResponse,
  Material_FilesUploader_ServerResponseSuccess,
  Course_View_Title,
  Course_View_NoCourses,
  Course_View_LoadingList,
  Course_View_StatusFilter,
  Course_View_DuplicateDetails,
  StatusFilter_All,
  StatusFilter_Expired,
  StatusFilter_Opening,
  StatusFilter_Coming,
  Course_Page_Title,
  Course_Page_AddUnit,
  Course_Page_UnitStatusFilter,
  Course_Page_LoadingMaterialList,
  Course_Page_ViewDescription,
  Course_Page_EditDetails,
  Course_Page_AddContent,
  Course_Page_NoAnyContent,
  Course_Page_Delete,
  Course_Page_DeleteWarning,
  Course_Page_DeleteSuccess,
  Course_Page_CourseNotFound,
  Course_Page_CourseOutdated,
  Course_Edit_LoadingData,
  Course_ContentPage_AppBarTitle,
  Course_ContentPage_LoadingAttachmentList,
  Course_ContentPage_StatusFilter,
  Course_ContentPage_Delete,
  Course_ContentPage_DeleteWarning,
  Course_ContentPage_DeleteSuccess,
  Course_ContentPage_OpenFile,
  Course_ContentPage_DownloadFile,
  Course_ContentPage_OpenWebsiteWarning_Title,
  Course_ContentPage_OpenWebsiteWarning,
  Course_ContentPage_NoAnyAttachment,
  Course_ContentPage_ContentNotFound,
  Course_ContentPage_ContentOutdated,
  Course_ContentPage_MarkedasComplete,
  Course_ContentPage_MarkedasNotComplete,
  Course_ContentPage_AttachmentNotFound,
  Course_ContentPage_EditDetails,
  Course_ContentPage_Editor_AppBarTitle,
  Course_ContentPage_Editor_LoadingData,
  ResetFormWarning,
  CourseCreator_Creator_AppBarTitle,
  CourseCreator_Creator_Title,
  CourseCreator_Creator_Desc,
  CourseCreator_Creator_Groups,
  CourseCreator_Creator_GroupUsers,
  CourseCreator_Creator_GroupUsers_NULL,
  CourseCreator_Creator_StartTime,
  CourseCreator_Creator_StartDate,
  CourseCreator_Creator_EndTime,
  CourseCreator_Creator_EndDate,
  CourseCreator_Creator_AddNewGroup,
  CourseCreator_Preview_AppBarTitle,
  CourseCreator_Preview_StartDateTime,
  CourseCreator_Preview_EndDateTime,
  CourseCreator_InsertSuccess,
  CourseCreator_Editor_AppBarTitle,
  EditingPreview_AppBarTitle,
  Editing_Confirm,
  CourseCreator_EditingSuccess,
  CourseCreator_EditingFail,
  DownloadFile_FileExists_Msg_Opening,
  DownloadFile_FileExists_Msg_Ending,
  DownloadFile_FileRedownload,
  DownloadFile_Success,
  DownloadFile_Fail,
  DownloadFile_WaitForServerResponse,
  DownloadFile_WaitForDownloadProcess,
  DownloadFile_FileDownloading,
  SendEmail,
  CourseUnitListPage_LoadingList,
  CourseUnitPage_AppBarTitle,
  CourseUnitPage_EditDetails,
  CourseUnitPage_DuplicateDetails,
  CourseUnitPage_Delete,
  CourseUnitPage_DeleteWarning,
  CourseUnitPage_DeleteSuccess,
  CourseUnitCreator_Creator_AppBarTitle,
  CourseUnitCreator_Creator_Title,
  CourseUnitCreator_Creator_Desc,
  CourseUnitCreator_Creator_StartTime,
  CourseUnitCreator_Creator_StartDate,
  CourseUnitCreator_Creator_EndTime,
  CourseUnitCreator_Creator_EndDate,
  CourseUnitCreator_Creator_SkipModuleSelection_Checkbox,
  CourseUnitCreator_Creator_SkipModuleSelection,
  CourseUnitCreator_Creator_SkipModuleSelection_Desc,
  CourseUnitCreator_Creator_SkipModuleSelection_Checkbox_Desc,
  CourseUnitCreator_Creator_SkipModuleSelection_Default,
  CourseUnitCreator_Creator_InsertSuccess,
  CourseUnitCreator_Editor_AppBarTitle,
  CourseUnitCreator_Creator_EditingSuccess,
  CourseUnitCreator_Preview_AppBarTitle,
  CourseUnitCreator_Preview_StartDateTime,
  CourseUnitCreator_Preview_EndDateTime,
  CourseUnitCreator_EditingFail,
  CourseUnit_Page_ViewDescription,
  UnitModule_Page_ViewDescription,
  CourseUnitListPage_UnitSelectionTitle,
  CourseUnitPage_ModuleSelectionTitle,
  ModulePage_AttachmentSelectionTitle,
  Survey_AppBarTitle,
  Survey_Editor_Edit_AppBarTitle,
  Survey_Editor_Create_AppBarTitle,
  Survey_Editor_Title,
  Survey_Editor_Desc,
  Survey_Editor_Link,
  Survey_Editor_LinkDesc,
  Survey_Editor_StartDate,
  Survey_Editor_StartTime,
  Survey_Editor_EndDate,
  Survey_Editor_EndTime,
  Survey_Editor_Preview_StartDateTime,
  Survey_Editor_Preview_EndDateTime,
  Survey_Editor_Creator_InsertSuccess,
  Survey_Editor_Creator_UpdateSuccess,
  Survey_Editor_Creator_Fail,
  Survey_Editor_LoadingSurveyData,
  Survey_ListPage_AppBarTitle,
  Survey_ListPage_NoSurvey,
  Survey_ListPage_LoadingList,
  Survey_ListPage_StatusFilter,
  Survey_ListPage_ViewSurvey,
  Survey_ListPage_DeleteSurvey,
  Survey_ListPage_DeleteSurvey_Warning_Opening,
  Survey_ListPage_DeleteSurvey_Warning_Ending,
  Survey_ListPage_DeleteSurvey_Success,
  Survey_ListPage_DuplicateDetails,
  Course_View_ViewCourse,
  CourseUnitListPage_ViewUnit,
  CourseUnitPage_ViewModule,
  Progress_Module_AttToal_Title,
  Progress_Unit_AttTotal_Title,
  Progress_Unit_ModuleTotal_Title,
  Progress_Course_AttTotal_Title,
  Progress_Course_UnitTotal_Title,
  Progress_Course_ModuleTotal_Title,
  Progress_Updating,
  Profiles_ViewCourseProgress_title,
  Profiles_ViewCourseProgress_Desc,
  Profiles_ViewSurvey_title,
  Profiles_ViewSurvey_Desc,
  Profiles_ChangePassword_title,
  Profiles_ChangePassword_Desc,
  Profiles_ChangePassword_DoubleCheck,
  Profiles_ChangePassword_DoubleCheck_Failed,
  Profiles_ChangePassword_Condition_Length,
  Profiles_ChangePassword_Condition_ContainUpper,
  Profiles_ChangePassword_Condition_ContainLower,
  Profiles_ChangePassword_Condition_SpecialCharacter,
  Profiles_ChangePassword_Success,
  Profiles_ChangePassword_Failed,
  Profiles_ChangePassword_Condition_Check_TopMsg,
  Profiles_ChangeDefaultEmail_title,
  Profiles_ChangeDefaultEmail_InBoxDesc,
  Profiles_ChangeDefaultEmail_Desc,
  Profiles_ChangeDefaultEmail_FormatError,
  Profiles_ChangeDefaultEmail_Success,
  Profiles_ChangeDefaultEmail_Exists,
  Profiles_ChangeDefaultEmail_Failed,
  SendResetPWRequest_BtnTitle,
  SendResetPWRequest_Title,
  SendResetPWRequest_Desc,
  SendResetPWRequest_Success,
  SendResetPWRequest_Failed,
  SendResetPWRequest_ACNotFound,
  SendResetPWRequest_ApplicationInvaild,
  SendResetPWRequest_Sending,
  SendValidationRequest_Failed,
  Profiles_NotificationManager_title,
  Profiles_NotificationManager_Insidetitle,
  Profiles_NotificationManager_Desc,
  Profiles_NotificationManager_ViewNotificationDesc,
  Profiles_NotificationManager_Delete,
  Profiles_NotificationManager_DeleteWarning,
  Profiles_NotificationManager_DeleteSuccess,
  Profiles_UserGroupSetting_title,
  Profiles_UserGroupSetting_Insidetitle,
  Profiles_UserGroupSetting_Desc,
  Profiles_UserGroupSetting_ViewUsers,
  Profiles_UserGroupSetting_Delete,
  Profiles_UserGroupSetting_DeleteWarning,
  Profiles_UserGroupSetting_DeleteSuccess,
  Profiles_SubGroup_Prefix,
  Profiles_SubGroup_NoGroup,
  NotificationManager_AddCourseReminder,
  NotificationManager_SettingCourseReminder_TimeTitle,
  NotificationManager_CourseReminderTitle,
  NotificationManager_CourseReminderContentOpening,
  NotificationManager_CourseReminderContentEnding,
  NotificationManager_AddLoginReminder,
  NotificationManager_ReminderAdded,
  NotificationManager_SettingCourseReminder_TimeFieldNull,
  Profiles_NotificationManager_TimeTitle_Opening,
  Profiles_NotificationManager_TimeTitle_Ending,
  GroupUser_GettingUsersList,
  GroupUser_Setting,
  GroupUser_ListTitle_Start,
  GroupUser_ListTitle_End,
  GroupUser_ListButton,
  GroupUser_SettingTitle_Start,
  GroupUser_Setting_UploadingToDB,
  GroupUser_Setting_Upload_Failed,
  GroupUser_Setting_Upload_Success,
  GroupUser_Setting_Upload_NameExits,
  GroupUser_Setting_Upload_NameNull,
  GroupUser_List_UsersCount_Title,
  Contact_Form_AppTitle,
  Contact_Form_Lable_Title,
  Contact_Form_Lable_Desc,
  Contact_Form_Lable_ReplyEmail,
  Contact_Form_Lable_ReplyEmail_Desc,
  Contact_Form_Lable_NameTitle,
  Contact_Form_Lable_Preview,
  Contact_Form_Lable_Send,
  Contact_Form_Lable_NameTitle_Mr,
  Contact_Form_Lable_NameTitle_Mrs,
  Contact_Form_Lable_NameTitle_Ms,
  Contact_Form_Lable_NameTitle_Miss,
  Contact_Form_Lable_NameTitle_Dr,
  Contact_Form_Sending,
  Contact_Form_Sent_Success,
  Contact_Form_Sent_Failed,
  Contact_Form_Sent_OverLimit,
  TechSupport_Label_Title,
  TechSupport_Label_Desc,
  TechSupport_DefaultTitle,
  TechSupport_Question_Title,
  TechSupport_Attachment_Title,
  TechSupport_Label_UserDeviceInformation,
  TechSupport_Label_UserDeviceModel,
  TechSupport_Label_UserDeviceVersion,
  TechSupport_Label_Manufacturer,
  ResendValidationEmailButtonTitle,
  ResendValidationEmail_Sending,
  ResendValidationEmail_Success,
}

// Localizations_String
final Map<Localizations_Language_Identifier,Map<Localizations_Text_Identifier,dynamic>> Localizations_Text =
{
  Localizations_Language_Identifier.Language_Eng:
  {
    Localizations_Text_Identifier.appTitle:"Testing SMP App",
    Localizations_Text_Identifier.ExitAppWarningText: "Are you sure you want to exit the application?",
    Localizations_Text_Identifier.loginIdHintText:"Account ID",
    Localizations_Text_Identifier.loginPwHintText : "Password",
    Localizations_Text_Identifier.InvitationHintText: "Invitation Code",
    Localizations_Text_Identifier.AcceptUserPolicyHintText: "Agree to User Terms ",
    Localizations_Text_Identifier.AcceptPrivacyPolicyHintText: "Agree to Privacy Policy",
    Localizations_Text_Identifier.UnAcceptedPolicyText: "You must agree to all terms before you can register",
    Localizations_Text_Identifier.loginButtonText : "Login",
    Localizations_Text_Identifier.loginRememberAccountText:"Remember My Account",
    Localizations_Text_Identifier.logoutButtonText : "Logout",
    Localizations_Text_Identifier.HomePageText : "Home",
    Localizations_Text_Identifier.EmailHintText : "Email",
    Localizations_Text_Identifier.FirstNameHintText : "First Name",
    Localizations_Text_Identifier.LastNameHintText : "Last Name",
    Localizations_Text_Identifier.NickNameHintText : "Nick Name",
    Localizations_Text_Identifier.GenderHintText: "Gender",
    Localizations_Text_Identifier.Signup_UserPolicyTitle: "User Terms",
    Localizations_Text_Identifier.Signup_PrivacyPolicyTitle: "Privacy Policy",
    Localizations_Text_Identifier.Signup_EmailManual:"Please enter the email address in the correct format\nFor example: email@example.com\n\nPlease note: You need to complete the email verification to log in to the system,\nso you must ensure that the email can receive the email normally,\notherwise you will not be able to complete the verification process.",
    Localizations_Text_Identifier.Signup_IDManual:"ID must consist of at least 8 characters and\nNo special characters are allowed",
    Localizations_Text_Identifier.Signup_PWManual:"The password must meet the following conditions:\n"
        "-The password must be at least 9 characters in length,\n"
        "-Must contain at least 1 Uppercase letter,\n"
        "-Must contain at least 1 Lowercase letter and, \n"
        "-Must contain at least 1 special character listed below\n*! # @ &",
    Localizations_Text_Identifier.Signup_InvitationCodeManual: "Please enter the invitation code attached to the invitation email.",
    Localizations_Text_Identifier.Signup_Confirmation_Title:"Submit Account Registration",
    Localizations_Text_Identifier.Signup_Confirmation_Desc:"Before submitting the registration form,\ncheck whether the information filled in the form is correct.\nAfter successful registration,\nyou will not be allowed to change user information (except email and password)\n\nPlease note: you need to complete email verification to log in to the system,\nyou must ensure that the email currently used to register your account can receive emails normally ,\notherwise you will not be able to complete the verification process.\n\nThe email address you entered is:\n ",
    Localizations_Text_Identifier.Signup_Confirmation_Confirm:"Submit",
    Localizations_Text_Identifier.Signup_Confirmation_Cancel:"Check Again",
    Localizations_Text_Identifier.signupButtonText : "Register",
    Localizations_Text_Identifier.ProfilesLabelText : "My Account",
    Localizations_Text_Identifier.Register_ProfilesLabelText: "Personal Data",
    Localizations_Text_Identifier.AccountLabelText : "Account Setting",
    Localizations_Text_Identifier.settingButtonText : "Setting",
    Localizations_Text_Identifier.languageButtonText : "Language",
    Localizations_Text_Identifier.autoLoginText: "Automatic Login",
    Localizations_Text_Identifier.NotificationPermission: "Push Notification",
    Localizations_Text_Identifier.NotificationPermission_Description: "The push notification function mainly informs you in the following situations:\n    1) When courses or questionnaires are available or updated,\n    2) Regularly remind you to participate in research.\nIt is recommended that you enable this function to avoid missing the latest information.",
    Localizations_Text_Identifier.NotificationPermission_Title: "Turn on Push Notifications",
    Localizations_Text_Identifier.NotificationPermission_Confirm: "Turn On",
    Localizations_Text_Identifier.NotificationPermission_Recommend: "Push Notification Function",
    Localizations_Text_Identifier.NotificationPermission_RecommendDescription: "This application has a push notification function\nYou can choose to enable this function in the 'Settings Page' to receive notifications from the system.\nThe push notification function mainly informs you in the following situations:\n    1) When courses or questionnaires are available or updated,\n    2) Regularly remind you to participate in research.\nIt is recommended that you enable this function to avoid missing the latest information.",
    Localizations_Text_Identifier.NotificationPermission_Recommend_ToSetting: "To Setting Page",
    Localizations_Text_Identifier.fontSize_Small: "S",
    Localizations_Text_Identifier.fontSize_Middle: "M",
    Localizations_Text_Identifier.fontSize_Large: "L",
    Localizations_Text_Identifier.fontSize_ExtraLarge: "XL",
    Localizations_Text_Identifier.fontSizeSelectorDefaultDesc: "Default font size suitable for this device: ",
    Localizations_Text_Identifier.fontSizeSelectorText: "Font Size",
    Localizations_Text_Identifier.fontSizeSelector_Warning: "The font size you choose is larger than the default font size for this device.\nChange to a larger font size may cause some text fails to display properly.\nAre you sure you want to change the font size? ",
    Localizations_Text_Identifier.loadingText : "Loading...",
    Localizations_Text_Identifier.SelectText : "Select",
    Localizations_Text_Identifier.Text_male : "Male",
    Localizations_Text_Identifier.Text_Female : "Female",
    Localizations_Text_Identifier.Text_Other : "Other",
    Localizations_Text_Identifier.Register_Success : "Registration Success!\nThe system has sent a verification email to your email address\nThe verification email may be classified as spam by the email service provider.\nIf you cannot find the email sent by auto@sme.dsgshk.com in your inbox,\nPlease check your spam.",
    Localizations_Text_Identifier.Register_Error_TopLine : "The following problems occurred in the registration process:\n",
    Localizations_Text_Identifier.Register_Error_EmailExists : "This email address is already registered\n",
    Localizations_Text_Identifier.Register_Error_UserExists : "This account ID has already been registered\n",
    Localizations_Text_Identifier.Register_Error_INVCodeError: "The system could not find the invitation code you entered. / \nThe invitation code you entered has expired.",
    Localizations_Text_Identifier.Register_Error_INVCodeLimited: "The number of uses of this invitation code has exceeded the limit\n",
    Localizations_Text_Identifier.Register_Error_IPLimited : "The system has detected that your IP has successfully registered an account within the last 24 hours, so you have been banned from registration.\n",
    Localizations_Text_Identifier.Register_Error_NotFillAll_TopLine : "The following fields have not been filled in:\n",
    Localizations_Text_Identifier.Login_Success : "Login Successfully!",
    Localizations_Text_Identifier.Login_Error_TopLine : "The login process has the following problems:\n",
    Localizations_Text_Identifier.Login_Error_IncorrectUserName : "Incorrect E-mail or Account ID\n",
    Localizations_Text_Identifier.Login_Error_IncorrectPassword : "Incorrect Password\n",
    Localizations_Text_Identifier.Login_Error_Unverified_Email: "Unverified Email\nPlease check the email you used when registering your account.\n\nIf you have recently changed the email address of your account, you also need to re-verify.\n\nIf you have not received the verification email sent by the system, you can click 'Resend Verification Email', and the system will resend the verification email later. ",
    Localizations_Text_Identifier.Login_Error_NotFillAll_TopLine : "The following fields have not been filled:\n",
    Localizations_Text_Identifier.Logout_Error_TopLine : "An unknown error occurred while logging out\n\nPlease try again",
    Localizations_Text_Identifier.Logout_Success: "Logout successfully!",
    Localizations_Text_Identifier.Connection_Error: "Unknown Connection Problem\n\nPlease Check Your Network Connection Or\nContact Our Technical Support.\n\n[Error Code: Unknown]",
    Localizations_Text_Identifier.Connection_Error_FormatException: "Unknown Connection Problem\n\nPlease Check Your Network Connection Or\nContact Our Technical Support.\n\n[Error Code: FormatException]",
    Localizations_Text_Identifier.Connection_Timeout: "Connection Timeout\n\nPlease Check Your Network Connection Or\n Contact Our Technical Support.\n\n[Error Code: Timeout]",
    Localizations_Text_Identifier.Connection_TokenChecking: "Checking Login Token...",
    Localizations_Text_Identifier.Connection_TokenError: "Your login token are invalid\nPlease login again\n\n[Error code: Expired Token]",
    Localizations_Text_Identifier.Connection_ReloginBtn: "Login Again",
    Localizations_Text_Identifier.Verifier_Loading : "Verifying Version...",
    Localizations_Text_Identifier.Verifier_Error_IncorrectAppCode_Android: "Verification Failed\n\nPlease press 'To Google Play'\nto download again from the Google Play or contact a technician for further assistance.",
    Localizations_Text_Identifier.Verifier_Error_IncorrectAppCode_IOS: "Verification Failed\n\nPlease press 'To AppStore''\nto download again from the AppStore or contact a technician for further assistance.",
    Localizations_Text_Identifier.Verifier_Error_IncorrectAppVersion_Android : "The app version is different from the server version\n\nPlease click 'To Google Play'\nto download the latest version from Google Play.",
    Localizations_Text_Identifier.Verifier_Error_IncorrectAppVersion_IOS : "The app version is different from the server version\n\nPlease click 'To AppStore'\nto download the latest version from AppStore.",
    Localizations_Text_Identifier.Tips_Warning: "Warning",
    Localizations_Text_Identifier.Tips_Success: "Success",
    Localizations_Text_Identifier.Tips_Error: "Error",
    Localizations_Text_Identifier.Confirm: "Confirm",
    Localizations_Text_Identifier.Cancel: "Cancel",
    Localizations_Text_Identifier.Profiles_Error_LoadingFailed: "Loading Profiles Failed\n\nPlease check network connection",
    Localizations_Text_Identifier.Material_NewLearningMaterial: "Create Module",
    Localizations_Text_Identifier.Material_TitleLabelText: "Module Title",
    Localizations_Text_Identifier.Material_DescLabelText: "Module Description",
    Localizations_Text_Identifier.Material_StartTimeLabelText : "Module Opening Time",
    Localizations_Text_Identifier.Material_StartDateLabelText : "Module Opening Date",
    Localizations_Text_Identifier.Material_EndTimeLabelText : "Module End Time",
    Localizations_Text_Identifier.Material_EndDateLabelText : "Module End Date",
    Localizations_Text_Identifier.Material_StartDateTimeLabelText : "Module Start Date and Time",
    Localizations_Text_Identifier.Material_EndDateTimeLabelText : "Module End Date and Time",
    Localizations_Text_Identifier.Material_DateTimeSelection_HintText : "Press 'Select' to enter",
    Localizations_Text_Identifier.Material_UploadAttachment: "Select Attachments",
    Localizations_Text_Identifier.Preview: "Preview",
    Localizations_Text_Identifier.Material_FilesSelecter_AddFiles: "Add",
    Localizations_Text_Identifier.Material_FilesSelecter_SizeWarningTitle : "The following files will be removed because they exceed the size limit (" + (fileSizeLimitInBytes/1024/1024).toString() + " MB):\n",
    Localizations_Text_Identifier.Material_FilesSelecter_OverLimitOfSelection : "You can only upload a total of " + fileTotalNumberLimit.toString() +" files",
    Localizations_Text_Identifier.Material_FilesSelecter_LoadingFilesList: "Loading Attachments...",
    Localizations_Text_Identifier.Material_FilesSelecter_Manual: "Click the 'Add' button to add attachments to be uploaded\nPress and hold the file to open the multi-select function to select more files\n\nMaximum number of uploaded files:" +
        fileTotalNumberLimit.toString() + "\nMaximum size of each file: " + (fileSizeLimitInBytes/1024/1024).toString() + " MB",
    Localizations_Text_Identifier.Material_FilesSelecter_FilesRemaining:"Remaining files limit:",
    Localizations_Text_Identifier.Material_FilesSelecter_ServerAttachment:"Existing attachments in the server",
    Localizations_Text_Identifier.Material_FilesSelecter_ServerAttachment_WillKeep:"The following attachments\nwill be retained",
    Localizations_Text_Identifier.Material_FilesSelecter_ServerAttachment_WillDelete:"The following attachments\nwill be deleted",
    Localizations_Text_Identifier.Material_FilesSelecter_ServerAttachment_Keep:"Keep",
    Localizations_Text_Identifier.Material_FilesSelecter_ServerAttachment_Delete:"Selected to delete",
    Localizations_Text_Identifier.Material_FilesSelecter_NewAttachment:"The attachments to be added",
    Localizations_Text_Identifier.Material_FilesSelecter_NewAttachment_WillAdd:"The following attachments\nwill be added",
    Localizations_Text_Identifier.Material_UploadLinks: "Select URL Links",
    Localizations_Text_Identifier.Material_FilesSelecter_AddLinks: "Add URL Link",
    Localizations_Text_Identifier.Material_FilesSelecter_AddLinksManual: "Click the 'Add URL Link' button to add a URL link that needs to be uploaded to the database\nThere is no limit to the number of upload links\n ",
    Localizations_Text_Identifier.Material_FilesSelecter_LoadingLinksList: "Loading URL Links",
    Localizations_Text_Identifier.Material_FilesSelecter_ServerLinks: "URL link data existing in the server",
    Localizations_Text_Identifier.Material_FilesSelecter_ServerLinks_WillKeep: "The following URL link data will be retained",
    Localizations_Text_Identifier.Material_FilesSelecter_ServerLinks_WillDelete: "The following URL link data will be deleted",
    Localizations_Text_Identifier.Material_FilesSelecter_ServerLinks_Keep: "Reserved URL link",
    Localizations_Text_Identifier.Material_FilesSelecter_ServerLinks_Delete: "URL link selected for deletion",
    Localizations_Text_Identifier.Material_FilesSelecter_NewLinks: "URL link to be added",
    Localizations_Text_Identifier.Material_FilesSelecter_NewLinks_WillAdd: "The following URL link data will be added to the server",
    Localizations_Text_Identifier.Material_FilesSelecter_NewLinks_Dialog_NameLabel: "Link Name",
    Localizations_Text_Identifier.Material_FilesSelecter_NewLinks_Dialog_URLLabel: "URL (Link)",
    Localizations_Text_Identifier.Material_UploadFormNotAllFill: "Please fill in all fields",
    Localizations_Text_Identifier.Material_UploadFormReset: "Reset Form",
    Localizations_Text_Identifier.Material_UploadFormReset_Warning: "Are you sure you want to clear all entered fields and selected attachments?",
    Localizations_Text_Identifier.Material_InsertLinkSuccess: "This link will be added to the database",
    Localizations_Text_Identifier.DateTimeSettingError_EndBeforeStart: "End date and time cannot be\nbefore or equal to\nOpening date and time\nPlease Reset",
    Localizations_Text_Identifier.Retry: "Retry",
    Localizations_Text_Identifier.GoToAppStore_IOS: "To AppStore",
    Localizations_Text_Identifier.GoToAppStore_Android: "To Google Play",
    Localizations_Text_Identifier.Exit: "Exit",
    Localizations_Text_Identifier.Exit_iOS_Warning: "iOS does not support the function of exiting the application\nPlease use the Home button to exit",
    Localizations_Text_Identifier.Close: "Close",
    Localizations_Text_Identifier.LoadingTitle: "Please Wait",
    Localizations_Text_Identifier.Internet_ConnectionTips: "You must be connected to the Internet before using this application.\n"
        "Please make sure to use it under a stable network.\n"
        "Otherwise, you may not be able to connect to the server.",
    Localizations_Text_Identifier.GoToApplicationSetting: "Go To Settings",
    Localizations_Text_Identifier.Permission_Titleforasking: "Please enable the following required permissions: \n\n",
    Localizations_Text_Identifier.Permission_askforStorage: "Storage: Allow the application to read folder and store the file to your device",
    Localizations_Text_Identifier.Permission_askforNotification: "Notification: Allow the application to use the notification function。",
    Localizations_Text_Identifier.Permission_isPermanentlyDenied: "Not allowed to use the required permissions\nPlease press 'Go to Settings'' to start application settings\nand manually enable all required permissions under permissions.\n\nWhen finished, please restart the application",
    Localizations_Text_Identifier.Permission_Endingforasking: "\n\nAfter confirming, please follow the instructions to allow the required permissions.",
    Localizations_Text_Identifier.Permission_NotificationDenied: "You have previously denied permission to allow push notifications, so the system failed to push the permission permission confirmation box again.\n\nIf you want to receive push notifications, please click 'Go to Settings' to open application settings and Turn on 'Notifications' permission manually.\nPlease return to the app to re-enable the push notification function when you are done. ",
    Localizations_Text_Identifier.Material_Preview_Title: "Upload Preview",
    Localizations_Text_Identifier.Material_Preview_EditDetails: "Edit Details",
    Localizations_Text_Identifier.Material_Preview_EditAttachment: "Edit Attachments",
    Localizations_Text_Identifier.Material_Preview_EditLinks: "Edit Links",
    Localizations_Text_Identifier.Material_Preview_NoAnyAttachment: "You have not added any attachments to this module\n\nIf you need to add attachments\nplease press 'Edit Attachments'",
    Localizations_Text_Identifier.ConfirmUpload: "Confirm",
    Localizations_Text_Identifier.Material_FilesUploader_Title: "Upload Status",
    Localizations_Text_Identifier.Material_FilesUploader_Uploading: "Uploading... ",
    Localizations_Text_Identifier.Material_FilesUploader_WaitforUpload: "Wait for Upload... ",
    Localizations_Text_Identifier.Material_FilesUploader_Success: "Upload successfully",
    Localizations_Text_Identifier.Material_FilesUploader_Fail: "Upload failed, click X to view more information.",
    Localizations_Text_Identifier.Material_FilesUploader_Retry: "Retry",
    Localizations_Text_Identifier.Material_FilesUploader_FinishSubmission: "Finish",
    Localizations_Text_Identifier.Material_FilesUploader_Inserting: "Adding to server...",
    Localizations_Text_Identifier.Material_FilesUploader_InsertSuccess: "The Content and Attachments of Module have been successfully added to the server",
    Localizations_Text_Identifier.Material_FilesUploader_InsertFail: "An error occurred while adding to the server, please try again",
    Localizations_Text_Identifier.Material_FilesUploader_LoadingServerResponse: "Waiting to initialize the upload process...",
    Localizations_Text_Identifier.Material_FilesUploader_ServerResponseSuccess: "The upload process has been initialized",
    Localizations_Text_Identifier.Course_View_Title: "My Course(s)",
    Localizations_Text_Identifier.Course_View_NoCourses: "There are currently no courses",
    Localizations_Text_Identifier.Course_View_StatusFilter: "Courses Status Filter",
    Localizations_Text_Identifier.Course_View_DuplicateDetails: "Duplicate Course",
    Localizations_Text_Identifier.StatusFilter_All:"All",
    Localizations_Text_Identifier.StatusFilter_Expired:"Expired",
    Localizations_Text_Identifier.StatusFilter_Opening:"Opening",
    Localizations_Text_Identifier.StatusFilter_Coming:"Coming",
    Localizations_Text_Identifier.Course_Page_Title: "Course Syllabus",
    Localizations_Text_Identifier.Course_Page_UnitStatusFilter: "Course Syllabus Status Filter",
    Localizations_Text_Identifier.Course_View_LoadingList: "Loading\nCourses...",
    Localizations_Text_Identifier.Course_Page_LoadingMaterialList:"Loading\nModule Contents...",
    Localizations_Text_Identifier.Course_Page_ViewDescription: "About the course",
    Localizations_Text_Identifier.Course_Page_EditDetails: "Edit Course",
    Localizations_Text_Identifier.Course_Page_AddContent: "Create Syllabus",
    Localizations_Text_Identifier.Course_Page_NoAnyContent: "There are currently no contents",
    Localizations_Text_Identifier.Course_Page_Delete: "Delete This Course",
    Localizations_Text_Identifier.Course_Page_DeleteWarning: "Are you sure you want to permanently delete\nthe entire course\n"
        "(including all the Syllabus content and attachments of this course)? \n\nOnce confirmed, it cannot be restored!",
    Localizations_Text_Identifier.Course_Page_DeleteSuccess: "This course and all its Syllabus content and attachments have been successfully deleted!",
    Localizations_Text_Identifier.Course_Page_CourseNotFound: "Content is not available\nReason：Contents Removed",
    Localizations_Text_Identifier.Course_Page_CourseOutdated: "Content is not available\nReason：Course has expired",
    Localizations_Text_Identifier.Course_Edit_LoadingData: "Loading Course Data...",
    Localizations_Text_Identifier.Course_ContentPage_AppBarTitle: "Syllabus Module",
    Localizations_Text_Identifier.Course_ContentPage_LoadingAttachmentList: "Loading\nModule Contents and Attachments...",
    Localizations_Text_Identifier.Course_ContentPage_StatusFilter: "Module Status Filter",
    Localizations_Text_Identifier.Course_ContentPage_Delete: "Delete this module and all its attachments",
    Localizations_Text_Identifier.Course_ContentPage_DeleteWarning: "Are you sure you want to permanently delete\nThis module and all its attachments? \n\nOnce confirmed, it cannot be restored!",
    Localizations_Text_Identifier.Course_ContentPage_DeleteSuccess: "This module and all its attachments have been successfully deleted!",
    Localizations_Text_Identifier.Course_ContentPage_OpenFile: "Open",
    Localizations_Text_Identifier.Course_ContentPage_DownloadFile: "Download",
    Localizations_Text_Identifier.Course_ContentPage_OpenWebsiteWarning_Title: "Network Traffic Warning",
    Localizations_Text_Identifier.Course_ContentPage_OpenWebsiteWarning: "Please note: You are about to go to another website,\n and this website may have videos or a large number of pictures attached, which will require a lot of network traffic.\nPlease try to use unlimited Wifi to browse this page\notherwise, your telecommunications provider may charge you an additional mobile network fees.",
    Localizations_Text_Identifier.Course_ContentPage_NoAnyAttachment: "There are currently no attachments",
    Localizations_Text_Identifier.Course_ContentPage_ContentNotFound: "This Module is not available\nReason：Contents Removed\nPlease click the button to the right of the title,\nto read the latest content from the server",
    Localizations_Text_Identifier.Course_ContentPage_ContentOutdated: "This Module is not available\nReason：Module has expired\nPlease click the button to the right of the title,\nto read the latest content from the server",
    Localizations_Text_Identifier.Course_ContentPage_AttachmentNotFound: "Unable to download this file from the server\nReason：File Removed\nPlease click the button to the right of the title,\nto read the latest content from the server",
    Localizations_Text_Identifier.Course_ContentPage_MarkedasComplete: "Mark as Completed",
    Localizations_Text_Identifier.Course_ContentPage_MarkedasNotComplete: "Mark as Incomplete",
    Localizations_Text_Identifier.Course_ContentPage_EditDetails: "Edit Module Details and Attachments",
    Localizations_Text_Identifier.Course_ContentPage_Editor_AppBarTitle: "Edit Module Content",
    Localizations_Text_Identifier.Course_ContentPage_Editor_LoadingData: "Loading\nModule Contents and its Attachments",
    Localizations_Text_Identifier.ResetFormWarning:"Are you sure you want to clear all entered fields？",
    Localizations_Text_Identifier.CourseCreator_Creator_AppBarTitle:"Create Course",
    Localizations_Text_Identifier.CourseCreator_Creator_Title:"Course Title",
    Localizations_Text_Identifier.CourseCreator_Creator_Desc:"Course Description",
    Localizations_Text_Identifier.CourseCreator_Creator_Groups:"Groups Authorized to access",
    Localizations_Text_Identifier.CourseCreator_Creator_GroupUsers:"\nUser List",
    Localizations_Text_Identifier.CourseCreator_Creator_GroupUsers_NULL:"There are no any users in this group",
    Localizations_Text_Identifier.CourseCreator_Creator_StartTime:"Course Opening Time",
    Localizations_Text_Identifier.CourseCreator_Creator_StartDate:"Course Opening Date",
    Localizations_Text_Identifier.CourseCreator_Creator_EndTime:"Course End Time",
    Localizations_Text_Identifier.CourseCreator_Creator_EndDate:"Course End Date",
    Localizations_Text_Identifier.CourseCreator_Creator_AddNewGroup:"Add New User Group",
    Localizations_Text_Identifier.CourseCreator_Preview_AppBarTitle: "Preview Course",
    Localizations_Text_Identifier.CourseCreator_Preview_StartDateTime:"Course Opening Date and Time",
    Localizations_Text_Identifier.CourseCreator_Preview_EndDateTime:"Course End Date and Time",
    Localizations_Text_Identifier.CourseCreator_InsertSuccess:"Course has been added to the database",
    Localizations_Text_Identifier.CourseCreator_Editor_AppBarTitle: "Edit Course",
    Localizations_Text_Identifier.EditingPreview_AppBarTitle: "Preview Change",
    Localizations_Text_Identifier.Editing_Confirm: "Confirm Change",
    Localizations_Text_Identifier.CourseCreator_EditingSuccess: "Course has been successfully updated to the database",
    Localizations_Text_Identifier.CourseCreator_EditingFail: "An unknown error occurred.\nThe course could not be added or updated to the database.\nPlease try again.",
    Localizations_Text_Identifier.DownloadFile_FileExists_Msg_Opening: "The system has detected that the file\n[",
    Localizations_Text_Identifier.DownloadFile_FileExists_Msg_Ending: "]\nalready exists，\n\nAre you sure you want to download and overwrite this file again？",
    Localizations_Text_Identifier.DownloadFile_FileRedownload: "Re-Download",
    Localizations_Text_Identifier.DownloadFile_Success:"Download completed\n\nThe file has been saved in \n'Download' folder",
    Localizations_Text_Identifier.DownloadFile_Fail:"An error occurred during the download process\nPlease check your network connection\nand try to download again.",
    Localizations_Text_Identifier.DownloadFile_WaitForServerResponse:"Waiting for the server to respond...",
    Localizations_Text_Identifier.DownloadFile_WaitForDownloadProcess: "Waiting for the \nInitialization of Download Process",
    Localizations_Text_Identifier.DownloadFile_FileDownloading:"\nFile downloading...",
    Localizations_Text_Identifier.SendEmail: "Contact The Research Teams",
    Localizations_Text_Identifier.CourseUnitListPage_LoadingList: "Loading\nCourse Syllabus...",
    Localizations_Text_Identifier.CourseUnitPage_AppBarTitle: "Course",
    Localizations_Text_Identifier.CourseUnitPage_Delete: "Delete Course Syllabus",
    Localizations_Text_Identifier.CourseUnitPage_DeleteWarning: "Are you sure you want to permanently delete\nThe entire syllabus\n"
        "(including all modules and all attachments in the unit)? \n\nOnce confirmed, it cannot be restored!",
    Localizations_Text_Identifier.CourseUnitPage_DeleteSuccess: "This course syllabus has been successfully deleted!",
    Localizations_Text_Identifier.CourseUnitPage_EditDetails: "Edit Syllabus",
    Localizations_Text_Identifier.CourseUnitPage_DuplicateDetails: "Duplicate Syllabus",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_AppBarTitle: "Create Course Syllabus",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_Title: "Syllabus Title",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_Desc: "Syllabus Description",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_StartTime: "Syllabus Opening Time",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_StartDate: "Syllabus Opening Date",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_EndTime: "Syllabus End Time",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_EndDate: "Syllabus End Date",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_SkipModuleSelection_Checkbox: "Skip the Syllabus Module Selection",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_SkipModuleSelection_Default: "Default (First Module)",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_SkipModuleSelection: "Redirect To",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_SkipModuleSelection_Desc: "The default will\nautomatically redirect to the first module\nIf you need to change,\nplease select the redirect module from the list.\nIt will not skip\nif there is no any Module in this Syllabus.",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_SkipModuleSelection_Checkbox_Desc: "Enable this function will force the module page to be skipped and automatically redirect to the specified module.\n\nThis function is only valid for normal users,\nadministrators will still enter the module selection page.\n\nPlease select the module for redirection under 'Redirect to'",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_InsertSuccess: "The course syllabus has been successfully added to the database",
    Localizations_Text_Identifier.CourseUnitCreator_Editor_AppBarTitle: "Edit Course Syllabus",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_EditingSuccess: "The course syllabus has been successfully updated to the database",
    Localizations_Text_Identifier.CourseUnitCreator_Preview_StartDateTime: "Syllabus Opening Date and Time",
    Localizations_Text_Identifier.CourseUnitCreator_Preview_EndDateTime: "Syllabus End Date and Time",
    Localizations_Text_Identifier.CourseUnitCreator_EditingFail: "An unknown error occurred.\nThe syllabus data could not be added or updated to the database.\nPlease try again.",
    Localizations_Text_Identifier.CourseUnit_Page_ViewDescription: "About the Syllabus",
    Localizations_Text_Identifier.UnitModule_Page_ViewDescription: "About the Module",
    Localizations_Text_Identifier.CourseUnitListPage_UnitSelectionTitle: "Course Syllabus",
    Localizations_Text_Identifier.CourseUnitPage_ModuleSelectionTitle: "Syllabus Modules Selection",
    Localizations_Text_Identifier.ModulePage_AttachmentSelectionTitle: "Module Attachments",
    Localizations_Text_Identifier.Survey_AppBarTitle: "My Surveys",
    Localizations_Text_Identifier.Survey_Editor_Edit_AppBarTitle:"Edit Survey",
    Localizations_Text_Identifier.Survey_Editor_Create_AppBarTitle:"Create Survey",
    Localizations_Text_Identifier.Survey_Editor_Title:"Survey Title",
    Localizations_Text_Identifier.Survey_Editor_Desc:"Survey Description",
    Localizations_Text_Identifier.Survey_Editor_Link:"Survey Link",
    Localizations_Text_Identifier.Survey_Editor_LinkDesc: "Please enter the link of the Google Form pre-filled response\n (refer to the user operation instructions)",
    Localizations_Text_Identifier.Survey_Editor_StartDate:"Survey Opening Date",
    Localizations_Text_Identifier.Survey_Editor_StartTime:"Survey Opening Time",
    Localizations_Text_Identifier.Survey_Editor_EndDate:"Survey End Date",
    Localizations_Text_Identifier.Survey_Editor_EndTime:"Survey End Time",
    Localizations_Text_Identifier.Survey_Editor_Preview_StartDateTime:"Survey Opening Date and Time",
    Localizations_Text_Identifier.Survey_Editor_Preview_EndDateTime:"Survey End Date and Time",
    Localizations_Text_Identifier.Survey_Editor_Creator_InsertSuccess: "Survey has been successfully added to the database",
    Localizations_Text_Identifier.Survey_Editor_Creator_UpdateSuccess: "Survey has been successfully updated to the database",
    Localizations_Text_Identifier.Survey_Editor_Creator_Fail: "An unknown error occurred.\nSurvey could not be added or updated to the database.\nPlease try again.",
    Localizations_Text_Identifier.Survey_Editor_LoadingSurveyData: "Loading\nDate of Survey",
    Localizations_Text_Identifier.Survey_ListPage_AppBarTitle: "Survey List",
    Localizations_Text_Identifier.Survey_ListPage_NoSurvey: "There are currently no survey",
    Localizations_Text_Identifier.Survey_ListPage_LoadingList: "Loading\nSurvey",
    Localizations_Text_Identifier.Survey_ListPage_StatusFilter: "Survey Status Filter",
    Localizations_Text_Identifier.Survey_ListPage_ViewSurvey: "View Survey",
    Localizations_Text_Identifier.Survey_ListPage_DeleteSurvey: "Delete This Survey",
    Localizations_Text_Identifier.Survey_ListPage_DeleteSurvey_Warning_Opening: "Are you sure you want to permanently delete Survey - \n[",
    Localizations_Text_Identifier.Survey_ListPage_DeleteSurvey_Warning_Ending: "]？\n\nOnce confirmed, it cannot be restored!",
    Localizations_Text_Identifier.Survey_ListPage_DeleteSurvey_Success: "\nSurvey has been successfully deleted.",
    Localizations_Text_Identifier.Survey_ListPage_DuplicateDetails: "Duplicate Survey",
    Localizations_Text_Identifier.Course_View_ViewCourse: "View Course Content",
    Localizations_Text_Identifier.CourseUnitListPage_ViewUnit: "View Course Syllabus",
    Localizations_Text_Identifier.CourseUnitPage_ViewModule: "View Module",
    Localizations_Text_Identifier.Progress_Module_AttToal_Title: "Progress of Module",
    Localizations_Text_Identifier.Progress_Unit_AttTotal_Title: "Total Progress of Syllabus",
    Localizations_Text_Identifier.Progress_Unit_ModuleTotal_Title: "Finished Modules",
    Localizations_Text_Identifier.Progress_Course_AttTotal_Title: "Total Progress of Course",
    Localizations_Text_Identifier.Progress_Course_UnitTotal_Title: "Finished Syllabus",
    Localizations_Text_Identifier.Progress_Course_ModuleTotal_Title: "Finished Syllabus Modules",
    Localizations_Text_Identifier.Progress_Updating: "Loading and Updating\nYour Course Progress...",
    Localizations_Text_Identifier.Profiles_ViewCourseProgress_title: "View All Courses",
    Localizations_Text_Identifier.Profiles_ViewCourseProgress_Desc: "Access course materials and view your progress",
    Localizations_Text_Identifier.Profiles_ViewSurvey_title: "View All Surveys",
    Localizations_Text_Identifier.Profiles_ViewSurvey_Desc: "Access and answer surveys",
    Localizations_Text_Identifier.Profiles_ChangePassword_title: "Change Password",
    Localizations_Text_Identifier.Profiles_ChangePassword_Desc: "Change the password used to log in to this account",
    Localizations_Text_Identifier.Profiles_ChangePassword_DoubleCheck: "Enter the password again",
    Localizations_Text_Identifier.Profiles_ChangePassword_DoubleCheck_Failed: "The entered passwords are inconsistent, please enter again.",
    Localizations_Text_Identifier.Profiles_ChangePassword_Condition_Length: "Password Length must be at least 9 characters\n",
    Localizations_Text_Identifier.Profiles_ChangePassword_Condition_ContainUpper: "Must contain at least 1 uppercase English letter\n",
    Localizations_Text_Identifier.Profiles_ChangePassword_Condition_ContainLower: "Must contain at least 1 lowercase English letter\n",
    Localizations_Text_Identifier.Profiles_ChangePassword_Condition_SpecialCharacter: "Must contain at least 1 special character listed below\n*! # @ &",
    Localizations_Text_Identifier.Profiles_ChangePassword_Success: "The password has been changed\nPlease log in to this account again with the new password.",
    Localizations_Text_Identifier.Profiles_ChangePassword_Failed: "An unknown error occurred during password change. Please try again.",
    Localizations_Text_Identifier.Profiles_ChangePassword_Condition_Check_TopMsg: "The password does not meet the following conditions, please input again",
    Localizations_Text_Identifier.Profiles_ChangeDefaultEmail_title: "Change Email Address",
    Localizations_Text_Identifier.Profiles_ChangeDefaultEmail_InBoxDesc: "Please enter a new email address below.\nIf you use an email to log in to your account, please use the new email to log in to your account after the change.\n\nPlease note: Changing the email address must be verified again.\nYou must ensure that the email can receive mail normally,\notherwise you will not be able to complete the verification process.",
    Localizations_Text_Identifier.Profiles_ChangeDefaultEmail_Desc: "Change the Default Email Address of this account",
    Localizations_Text_Identifier.Profiles_ChangeDefaultEmail_FormatError: "The email address you entered is in the Wrong Format\nPlease enter again\n\nThe email address format should be like:\nname@example.com",
    Localizations_Text_Identifier.Profiles_ChangeDefaultEmail_Success: "The default email address has been changed\nPlease log in again\n\nIf you use an email login account\nPlease use the changed email to login account\n\nIn addition, the system has sent a verification email to the email address you changed\nYou must complete the verification before you can log in.\nThe email may be classified as spam by the email service provider.\nIf you can’t find it in your inbox Mail sent by auto@sme.dsgshk.com\nPlease check your spam. ",
    Localizations_Text_Identifier.Profiles_ChangeDefaultEmail_Exists: "This email address is already in use.\nPlease Try with another Email.",
    Localizations_Text_Identifier.Profiles_ChangeDefaultEmail_Failed: "An unknown error occurred while changing the email address. Please try again.",
    Localizations_Text_Identifier.SendResetPWRequest_BtnTitle: "Forget Password?",
    Localizations_Text_Identifier.SendResetPWRequest_Title: "Reset Password",
    Localizations_Text_Identifier.SendResetPWRequest_Desc: "If you forget your account password\nPlease enter your username / email below\nThe system will send a password reset confirmation letter to the email you used when you registered your account.",
    Localizations_Text_Identifier.SendResetPWRequest_Success: "The confirmation letter for resetting the password\nhas been sent to the email you used to register your account",
    Localizations_Text_Identifier.SendResetPWRequest_Failed: "An unknown error occurred during application. Please try again.",
    Localizations_Text_Identifier.SendResetPWRequest_ACNotFound: "The system could not find this account or email address /\nthe email address does not match the account record,\nplease enter again.",
    Localizations_Text_Identifier.SendResetPWRequest_ApplicationInvaild: "Application verification failed\nPlease update the application to the latest version or download again.",
    Localizations_Text_Identifier.SendResetPWRequest_Sending: "The system is processing your application",
    Localizations_Text_Identifier.SendValidationRequest_Failed: "The account already exists\nbut the system failed to send the verification email due to a connection problem\nplease try again.\n\nIf you have this problem during registration\nplease return to the login page and\ntry Log in to your account to get a verification email.",
    Localizations_Text_Identifier.Profiles_NotificationManager_title: "Manage Course Reminders",
    Localizations_Text_Identifier.Profiles_NotificationManager_Insidetitle: "Reminders",
    Localizations_Text_Identifier.Profiles_NotificationManager_Desc: "View or Delete\nCourse Notifications and Reminders",
    Localizations_Text_Identifier.Profiles_NotificationManager_ViewNotificationDesc: "Reminder Contents",
    Localizations_Text_Identifier.Profiles_NotificationManager_Delete: "Delete Reminder",
    Localizations_Text_Identifier.Profiles_NotificationManager_DeleteWarning: "Are you sure you want to delete this reminder?",
    Localizations_Text_Identifier.Profiles_NotificationManager_DeleteSuccess: "\nThis reminder has been successfully deleted",
    Localizations_Text_Identifier.Profiles_UserGroupSetting_title: "User Group Manager",
    Localizations_Text_Identifier.Profiles_UserGroupSetting_Desc: "View, add or delete\nUser Groups and Member lists",
    Localizations_Text_Identifier.Profiles_UserGroupSetting_ViewUsers: "View User List",
    Localizations_Text_Identifier.Profiles_UserGroupSetting_Delete: "Delete This User Group",
    Localizations_Text_Identifier.Profiles_UserGroupSetting_DeleteWarning: "Are you sure you want to delete the following group?\n",
    Localizations_Text_Identifier.Profiles_UserGroupSetting_DeleteSuccess: "The following group have been successfully deleted\n",
    Localizations_Text_Identifier.Profiles_SubGroup_Prefix: "Joined Group:",
    Localizations_Text_Identifier.Profiles_SubGroup_NoGroup: "You have not joined any group",
    Localizations_Text_Identifier.NotificationManager_AddCourseReminder: "Set a Reminder",
    Localizations_Text_Identifier.NotificationManager_SettingCourseReminder_TimeTitle: "Daily Reminder Time",
    Localizations_Text_Identifier.NotificationManager_AddLoginReminder: "Add Login Reminder",
    Localizations_Text_Identifier.NotificationManager_CourseReminderTitle: "Daily Course Reminder - ",
    Localizations_Text_Identifier.NotificationManager_CourseReminderContentOpening: "Please remember to log in to your account, and\nContinue to participate and browse the course content!",
    Localizations_Text_Identifier.NotificationManager_ReminderAdded: "\nThe reminder for the above course has been successfully added",
    Localizations_Text_Identifier.NotificationManager_SettingCourseReminder_TimeFieldNull: "Please Set the Daily Reminder Time first",
    Localizations_Text_Identifier.Profiles_NotificationManager_TimeTitle_Opening: "The Reminder will be Displayed at ",
    Localizations_Text_Identifier.Profiles_NotificationManager_TimeTitle_Ending: " Every Day",
    Localizations_Text_Identifier.GroupUser_Setting: "Set the list of User Group",
    Localizations_Text_Identifier.GroupUser_ListTitle_Start: "Setting \n",
    Localizations_Text_Identifier.GroupUser_ListTitle_End: "\nUser List",
    Localizations_Text_Identifier.GroupUser_ListButton: "Click Here To \nSet the User List of Above Group",
    Localizations_Text_Identifier.GroupUser_SettingTitle_Start: "Current Group:\n",
    Localizations_Text_Identifier.GroupUser_Setting_UploadingToDB: "Updating User List...",
    Localizations_Text_Identifier.GroupUser_Setting_Upload_Failed: "Update failed, Please try again",
    Localizations_Text_Identifier.GroupUser_Setting_Upload_Success: "The list has been successfully updated to the database.",
    Localizations_Text_Identifier.GroupUser_Setting_Upload_NameExits: "This group already exists,\nplease change to another name",
    Localizations_Text_Identifier.GroupUser_Setting_Upload_NameNull: "The group name cannot be empty,\nplease enter the group name first",
    Localizations_Text_Identifier.GroupUser_List_UsersCount_Title: "Number of Group Members: ",
    Localizations_Text_Identifier.Contact_Form_Lable_Title: "Email Title",
    Localizations_Text_Identifier.Contact_Form_Lable_Desc: "Email Content",
    Localizations_Text_Identifier.Contact_Form_Lable_ReplyEmail: "Email address to receive reply",
    Localizations_Text_Identifier.Contact_Form_Lable_ReplyEmail_Desc: "The system has preset the email you used when registering\nIf you want to receive a reply via another email, please change this email address",
    Localizations_Text_Identifier.Contact_Form_Lable_NameTitle: "Name Title",
    Localizations_Text_Identifier.Contact_Form_Lable_Preview: "Preview Email",
    Localizations_Text_Identifier.Contact_Form_Lable_Send: "Send Email",
    Localizations_Text_Identifier.Contact_Form_Lable_NameTitle_Mr: "Mr",
    Localizations_Text_Identifier.Contact_Form_Lable_NameTitle_Mrs: "Mrs",
    Localizations_Text_Identifier.Contact_Form_Lable_NameTitle_Ms: "Ms",
    Localizations_Text_Identifier.Contact_Form_Lable_NameTitle_Miss: "Miss",
    Localizations_Text_Identifier.Contact_Form_Lable_NameTitle_Dr: "Dr",
    Localizations_Text_Identifier.Contact_Form_Sending:"Sending Contact Email...",
    Localizations_Text_Identifier.Contact_Form_Sent_Success: "Thank you for your inquiry.\nThe email has been sent successfully. Please wait patiently for the reply from the research team\n\nA copy of the email has been sent to your email for your records.",
    Localizations_Text_Identifier.Contact_Form_Sent_Failed: "The email was not sent successfully, please try again.\n\nIf it still fails to send, please take a screenshot of this screen as an attachment, and then contact a technician.",
    Localizations_Text_Identifier.Contact_Form_Sent_OverLimit: "Based on our Fair Usage Policy(FUP), each user can only send up to 10 queries per day.\n\nThe query you have sent has exceeded the limit, so the email was not sent successfully.\nPlease try again tomorrow. \n",
    Localizations_Text_Identifier.TechSupport_Label_Title: "Technical Support",
    Localizations_Text_Identifier.TechSupport_Label_Desc: "Report error messages or problems\nrelated to servers, programs, etc.\nto the technicians for further support",
    Localizations_Text_Identifier.TechSupport_DefaultTitle: "Please briefly describe the technical problem here",
    Localizations_Text_Identifier.TechSupport_Question_Title: "Please elaborate on the technical issues in this section",
    Localizations_Text_Identifier.TechSupport_Attachment_Title: "If there are pictures to help explain the above technical problems, please add the relevant pictures to the attachment.",
    Localizations_Text_Identifier.TechSupport_Label_UserDeviceInformation: "User Device Information：\n",
    Localizations_Text_Identifier.TechSupport_Label_UserDeviceModel: "Device Model: ",
    Localizations_Text_Identifier.TechSupport_Label_UserDeviceVersion: "Device Version: ",
    Localizations_Text_Identifier.TechSupport_Label_Manufacturer: "Device Manufacturer: ",
    Localizations_Text_Identifier.ResendValidationEmailButtonTitle: "Resend Verification Email",
    Localizations_Text_Identifier.ResendValidationEmail_Success: "The system has resend the verification email to your email address\nThe email may be classified as spam by the email service provider.\nIf you cannot find the email sent by auto@sme.dsgshk.com in your inbox,\nPlease check your spam.",
    Localizations_Text_Identifier.ResendValidationEmail_Sending: "The system is processing your request, please wait a moment",
  },
  Localizations_Language_Identifier.Language_TC:
  {
    Localizations_Text_Identifier.appTitle:"Testing SMP App",
    Localizations_Text_Identifier.ExitAppWarningText: "你確定要退出應用程式嗎？",
    Localizations_Text_Identifier.loginIdHintText:"帳號",
    Localizations_Text_Identifier.loginPwHintText : "密碼",
    Localizations_Text_Identifier.InvitationHintText: "邀請碼",
    Localizations_Text_Identifier.AcceptUserPolicyHintText: "同意用戶條款",
    Localizations_Text_Identifier.AcceptPrivacyPolicyHintText: "同意隱私權條款",
    Localizations_Text_Identifier.UnAcceptedPolicyText: "你必須同意所有條款才可進行註冊",
    Localizations_Text_Identifier.loginButtonText : "登入",
    Localizations_Text_Identifier.loginRememberAccountText:"記住帳號資訊",
    Localizations_Text_Identifier.logoutButtonText : "登出",
    Localizations_Text_Identifier.HomePageText : "主頁",
    Localizations_Text_Identifier.EmailHintText : "電子郵件",
    Localizations_Text_Identifier.FirstNameHintText : "名字",
    Localizations_Text_Identifier.LastNameHintText : "姓氏",
    Localizations_Text_Identifier.NickNameHintText : "暱稱",
    Localizations_Text_Identifier.GenderHintText: "性別",
    Localizations_Text_Identifier.Signup_UserPolicyTitle: "用戶條款",
    Localizations_Text_Identifier.Signup_PrivacyPolicyTitle: "隱私權條款",
    Localizations_Text_Identifier.Signup_EmailManual:"請按正確的格式輸入電郵地址\n例如: email@example.com\n\n請注意：你需完成郵件驗證才能登入系統，\n因此你必須確保該電郵能正常收取郵件，\n否則你將無法完成驗證程序",
    Localizations_Text_Identifier.Signup_IDManual:"ID需至少由8個字符組成\n且不允許輸入任何特殊字符",
    Localizations_Text_Identifier.Signup_PWManual:"密碼必須符合以下條件:\n-密碼長度最少為9個字符\n-必須包含至少 1 個大階英文字母\n-必須包含至少 1 個小階英文字母 及 \n-必須包含至少 1 個以下列明的特殊字符\n* ! # @ &",
    Localizations_Text_Identifier.Signup_InvitationCodeManual: "請輸入附於邀請郵件中的邀請碼",
    Localizations_Text_Identifier.Signup_Confirmation_Title:"提交帳號註冊申請",
    Localizations_Text_Identifier.Signup_Confirmation_Desc:"請於提交註冊表格前，\n檢查表格內所填寫的資料是否正確無誤。\n成功註冊後，\n你將不允許更改用戶資料\n（除電子郵件及密碼外)\n\n請注意：你需完成郵件驗證才能登入系統，因此你必須確保用作註冊帳號的電郵能正常收取郵件，否則你將無法完成驗證程序。\n\n你所輸入的電子郵件地址為:\n",
    Localizations_Text_Identifier.Signup_Confirmation_Confirm:"確定註冊",
    Localizations_Text_Identifier.Signup_Confirmation_Cancel:"再次檢查",
    Localizations_Text_Identifier.signupButtonText : "註冊",
    Localizations_Text_Identifier.ProfilesLabelText : "我的帳號",
    Localizations_Text_Identifier.Register_ProfilesLabelText: "個人檔案",
    Localizations_Text_Identifier.AccountLabelText : "帳號設定",
    Localizations_Text_Identifier.settingButtonText : "設定",
    Localizations_Text_Identifier.languageButtonText : "語言",
    Localizations_Text_Identifier.autoLoginText: "自動登入",
    Localizations_Text_Identifier.NotificationPermission: "推送通知",
    Localizations_Text_Identifier.NotificationPermission_Description: "推送通知功能主要在以下情況通知您：\n    1)課程或問卷上架或更新時，\n    2)定時提醒您參與研究。\n建議您開啟此功能以免錯過最新資訊。",
    Localizations_Text_Identifier.NotificationPermission_Title: "開啟推送通知功能",
    Localizations_Text_Identifier.NotificationPermission_Confirm: "開啟",
    Localizations_Text_Identifier.NotificationPermission_Recommend: "推送通知功能",
    Localizations_Text_Identifier.NotificationPermission_RecommendDescription: "本應用程式設有推送通知功能\n您可於「設定頁」選擇開啟此功能以接收來自系統的通知\n推送通知功能主要在以下情況通知您：\n    1)課程或問卷上架或更新時，\n    2)定時提醒您參與研究。\n建議您開啟此功能以免錯過最新資訊。",
    Localizations_Text_Identifier.NotificationPermission_Recommend_ToSetting: "前往設定頁",
    Localizations_Text_Identifier.fontSize_Small: "小",
    Localizations_Text_Identifier.fontSize_Middle: "中",
    Localizations_Text_Identifier.fontSize_Large: "大",
    Localizations_Text_Identifier.fontSize_ExtraLarge: "特大",
    Localizations_Text_Identifier.fontSizeSelectorDefaultDesc: "預設合適此裝置的字體大小: ",
    Localizations_Text_Identifier.fontSizeSelectorText: "字體大小",
    Localizations_Text_Identifier.fontSizeSelector_Warning: "你所選擇的字體大小比預設合適此裝置的字體大小較大，\n改變至較大的字體大小將可能會導致某些文字未能正常顯示。\n你確定要改變字體大小嗎？",
    Localizations_Text_Identifier.loadingText : "載入中...",
    Localizations_Text_Identifier.SelectText : "選擇",
    Localizations_Text_Identifier.Text_male : "男性",
    Localizations_Text_Identifier.Text_Female : "女性",
    Localizations_Text_Identifier.Text_Other : "其他",
    Localizations_Text_Identifier.Register_Success : "註冊成功!\n系統已發送驗證郵件至您的電子郵箱\n驗證郵件或有可能被電子郵件服務供應商列為垃圾郵件，\n若您未能在收件箱找到由 auto@sme.dsgshk.com 所發出的郵件，\n請檢查您的垃圾郵件。",
    Localizations_Text_Identifier.Register_Error_TopLine : "註冊程序出現以下問題:\n",
    Localizations_Text_Identifier.Register_Error_EmailExists : "此電郵地址已被註冊\n",
    Localizations_Text_Identifier.Register_Error_UserExists : "此帳號已被註冊\n",
    Localizations_Text_Identifier.Register_Error_INVCodeError: "系統找不到您所輸入的邀請碼 / \n或您所輸入的邀請碼已失效",
    Localizations_Text_Identifier.Register_Error_INVCodeLimited: "此邀請碼的使用次數已超出上限\n",
    Localizations_Text_Identifier.Register_Error_IPLimited : "系統檢測到你的IP已在最近24小時內成功註冊一次帳號，因此你已被禁止註冊。\n",
    Localizations_Text_Identifier.Register_Error_NotFillAll_TopLine : "以下欄位尚未填寫:\n",
    Localizations_Text_Identifier.Login_Success : "登入成功!",
    Localizations_Text_Identifier.Login_Error_TopLine : "登入程序出現以下問題:\n",
    Localizations_Text_Identifier.Login_Error_IncorrectUserName : "電子郵件或帳號輸入錯誤\n",
    Localizations_Text_Identifier.Login_Error_IncorrectPassword : "密碼錯誤\n",
    Localizations_Text_Identifier.Login_Error_Unverified_Email: "電子郵件未經驗證，\n"+
        "請檢查你註冊帳號時所用的電子郵箱。\n"+
        "如你最近曾更改過帳號的電子郵件地址，亦需重新驗證。"+
            "\n\n如你未收到由系統發送的驗證郵件，\n"+
            "你可按下方「重新發送驗證郵件」，\n"+
                "系統將會於稍後重新發送驗證郵件。",
    Localizations_Text_Identifier.Login_Error_NotFillAll_TopLine : "以下欄位尚未填寫:\n",
    Localizations_Text_Identifier.Logout_Error_TopLine : "登出時出現未知錯誤\n\n請重新嘗試",
    Localizations_Text_Identifier.Logout_Success: "登出成功!",
    Localizations_Text_Identifier.Connection_Error: "連接伺服器出現未知問題\n\n請檢查你的網絡連接\n或尋求技術支援。\n\n[錯誤代碼: Unknown]",
    Localizations_Text_Identifier.Connection_Error_FormatException: "連接伺服器出現未知問題\n\n請檢查你的網絡連接\n或尋求技術支援。\n\n[錯誤代碼: FormatException]",
    Localizations_Text_Identifier.Connection_Timeout: "連接伺服器時超出時限\n\n請檢查你的網絡連接並重試\n或尋求技術支援。\n\n[錯誤代碼: Timeout]",
    Localizations_Text_Identifier.Connection_TokenChecking: "正在檢查登入憑證... ",
    Localizations_Text_Identifier.Connection_TokenError: "您的登入憑證已失效\n請重新登入\n\n[錯誤代碼: Expired Token]",
    Localizations_Text_Identifier.Connection_ReloginBtn: "重新登入",
    Localizations_Text_Identifier.Verifier_Loading : "版本驗證中...",
    Localizations_Text_Identifier.Verifier_Error_IncorrectAppCode_Android: "應用程式驗證失敗\n\n請按「前往 Google Play」\n至應用程式商店重新下載或聯絡技術人員以獲進一步協助。",
    Localizations_Text_Identifier.Verifier_Error_IncorrectAppCode_IOS: "應用程式驗證失敗\n\n請按「前往 AppStore」\n至應用程式商店重新下載或聯絡技術人員以獲進一步協助。",
    Localizations_Text_Identifier.Verifier_Error_IncorrectAppVersion_Android : "應用程式版本與伺服器版本不相同\n\n請按「前往 Google Play」\n至應用程式商店下載最新版本。",
    Localizations_Text_Identifier.Verifier_Error_IncorrectAppVersion_IOS : "應用程式版本與伺服器版本不相同\n\n請按「前往 AppStore」\n至應用程式商店下載最新版本。",
    Localizations_Text_Identifier.Tips_Warning: "警告",
    Localizations_Text_Identifier.Tips_Success: "成功",
    Localizations_Text_Identifier.Tips_Error: "錯誤",
    Localizations_Text_Identifier.Confirm: "確定",
    Localizations_Text_Identifier.Cancel: "取消",
    Localizations_Text_Identifier.Profiles_Error_LoadingFailed: "讀取用戶資料失敗\n\n請檢查網絡連接",
    Localizations_Text_Identifier.Material_NewLearningMaterial: "新增章節組件",
    Localizations_Text_Identifier.Material_TitleLabelText: "章節組件標題",
    Localizations_Text_Identifier.Material_DescLabelText: "章節組件簡介",
    Localizations_Text_Identifier.Material_RequiredTimeLabelText : "預計完成所需時間 (小時)",
    Localizations_Text_Identifier.Material_StartTimeLabelText : "章節組件開放時間",
    Localizations_Text_Identifier.Material_StartDateLabelText : "章節組件開放日期",
    Localizations_Text_Identifier.Material_EndTimeLabelText : "章節組件結束時間",
    Localizations_Text_Identifier.Material_EndDateLabelText : "章節組件結束日期",
    Localizations_Text_Identifier.Material_StartDateTimeLabelText : "章節組件開放時期",
    Localizations_Text_Identifier.Material_EndDateTimeLabelText : "章節組件完結時期",
    Localizations_Text_Identifier.Material_DateTimeSelection_HintText : "按「選擇」進行輸入",
    Localizations_Text_Identifier.Material_UploadAttachment: "選擇附件",
    Localizations_Text_Identifier.Preview: "預覽",
    Localizations_Text_Identifier.Material_FilesSelecter_AddFiles: "增加",
    Localizations_Text_Identifier.Material_FilesSelecter_SizeWarningTitle : "以下檔案因大小超出可上傳上限 (" + (fileSizeLimitInBytes/1024/1024).toString() + " MB)\n將會被移除：\n",
    Localizations_Text_Identifier.Material_FilesSelecter_OverLimitOfSelection : "你最多只能上傳合共 " + fileTotalNumberLimit.toString() +" 個檔案",
    Localizations_Text_Identifier.Material_FilesSelecter_LoadingFilesList: "正在讀取附件列表中...",
    Localizations_Text_Identifier.Material_FilesSelecter_Manual: "點擊「增加」按鈕以新增需上傳的附件\n按住檔案可開啟複選功能以選擇更多檔案\n\n上傳檔案數量上限：" +
        fileTotalNumberLimit.toString() + "\n每個檔案大小上限: " + (fileSizeLimitInBytes/1024/1024).toString() + " MB",
    Localizations_Text_Identifier.Material_FilesSelecter_FilesRemaining:"剩餘上傳檔案限額: ",
    Localizations_Text_Identifier.Material_FilesSelecter_ServerAttachment:"現存於伺服器內的附件",
    Localizations_Text_Identifier.Material_FilesSelecter_ServerAttachment_WillKeep:"以下附件將會保留",
    Localizations_Text_Identifier.Material_FilesSelecter_ServerAttachment_WillDelete:"以下附件將會刪除",
    Localizations_Text_Identifier.Material_FilesSelecter_ServerAttachment_Keep:"保留",
    Localizations_Text_Identifier.Material_FilesSelecter_ServerAttachment_Delete:"已選擇刪除",
    Localizations_Text_Identifier.Material_FilesSelecter_NewAttachment:"欲新增之附件",
    Localizations_Text_Identifier.Material_FilesSelecter_NewAttachment_WillAdd:"以下附件將會增加至伺服器",
    Localizations_Text_Identifier.Material_UploadLinks: "選擇連結",
    Localizations_Text_Identifier.Material_FilesSelecter_AddLinks: "增加連結",
    Localizations_Text_Identifier.Material_FilesSelecter_AddLinksManual: "點擊「增加連結」按鈕以新增需上傳至資料庫的網址連結\n上傳連結並無數量上限\n",
    Localizations_Text_Identifier.Material_FilesSelecter_LoadingLinksList: "正在讀取網址連結列表中...",
    Localizations_Text_Identifier.Material_FilesSelecter_ServerLinks: "現存於伺服器內的網址連結資料",
    Localizations_Text_Identifier.Material_FilesSelecter_ServerLinks_WillKeep: "以下網址連結資料將會保留",
    Localizations_Text_Identifier.Material_FilesSelecter_ServerLinks_WillDelete: "以下網址連結資料將會刪除",
    Localizations_Text_Identifier.Material_FilesSelecter_ServerLinks_Keep: "保留的網址連結",
    Localizations_Text_Identifier.Material_FilesSelecter_ServerLinks_Delete: "已選擇刪除的網址連結",
    Localizations_Text_Identifier.Material_FilesSelecter_NewLinks: "欲新增之網址連結",
    Localizations_Text_Identifier.Material_FilesSelecter_NewLinks_WillAdd: "以下網址連結資料將會增加至伺服器",
    Localizations_Text_Identifier.Material_FilesSelecter_NewLinks_Dialog_NameLabel: "連結名稱",
    Localizations_Text_Identifier.Material_FilesSelecter_NewLinks_Dialog_URLLabel: "網址",
    Localizations_Text_Identifier.Material_UploadFormNotAllFill: "請先填寫所有欄位",
    Localizations_Text_Identifier.Material_UploadFormReset: "重新輸入表格",
    Localizations_Text_Identifier.Material_UploadFormReset_Warning: "你確定要清除所有已輸入欄位及已選擇的附件嗎？",
    Localizations_Text_Identifier.Material_InsertLinkSuccess: "此連結將會新增至資料庫",
    Localizations_Text_Identifier.DateTimeSettingError_EndBeforeStart: "完結日期及時間不能\n早於或等於\n開放日期及時間\n請重新設定",
    Localizations_Text_Identifier.Retry: "重試",
    Localizations_Text_Identifier.GoToAppStore_IOS: "前往 AppStore",
    Localizations_Text_Identifier.GoToAppStore_Android: "前往 Google Play",
    Localizations_Text_Identifier.Exit: "退出",
    Localizations_Text_Identifier.Exit_iOS_Warning: "iOS系統不支援退出應用程式的功能\n請自行使用Home鍵退出",
    Localizations_Text_Identifier.Close: "關閉",
    Localizations_Text_Identifier.LoadingTitle: "請稍等",
    Localizations_Text_Identifier.Internet_ConnectionTips: "使用本應用程式之前必須連接互聯網，\n請確保於網路穩定狀態下使用，\n否則有可能未能連接到伺服器。",
    Localizations_Text_Identifier.GoToApplicationSetting: "前往設定",
    Localizations_Text_Identifier.Permission_Titleforasking: "請開啟以下所需權限: \n\n",
    Localizations_Text_Identifier.Permission_askforStorage: "儲存: 以儲存下載的檔案到你的裝置及使用從裝置內選取檔案之功能。",
    Localizations_Text_Identifier.Permission_askforNotification: "通知: 以使用通知欄功能。",
    Localizations_Text_Identifier.Permission_isPermanentlyDenied: "未獲允許使用所需要之權限\n請按「前往設定」以開始應用程式設定\n並於權限手動開啟所有所需權限。",
    Localizations_Text_Identifier.Permission_Endingforasking: "\n\n按下確認後請根據指示允許所需權限。",
    Localizations_Text_Identifier.Permission_NotificationDenied: "你先前曾拒絕允許推送通知權限，因此系統未能再次推送權限允許確認方塊。\n\n若你希望收取推送通知，請按「前往設定」以開始應用程式設定並手動開啟「通知」權限。\n完成後請返回應用程式以重新開啟推送通知功能。",
    Localizations_Text_Identifier.Material_Preview_Title: "上傳預覽",
    Localizations_Text_Identifier.Material_Preview_EditDetails: "修改內容",
    Localizations_Text_Identifier.Material_Preview_EditAttachment: "修改需上傳之附件",
    Localizations_Text_Identifier.Material_Preview_EditLinks: "修改需上傳之連結",
    Localizations_Text_Identifier.Material_Preview_NoAnyAttachment: "你並沒有為此課程內容加入任何附件\n\n如需新增附件\n請按下「修改需上傳之附件」",
    Localizations_Text_Identifier.ConfirmUpload: "確定上傳",
    Localizations_Text_Identifier.Material_FilesUploader_Title: "上傳附件狀況",
    Localizations_Text_Identifier.Material_FilesUploader_Uploading: "上傳中... ",
    Localizations_Text_Identifier.Material_FilesUploader_WaitforUpload: "等待上傳中... ",
    Localizations_Text_Identifier.Material_FilesUploader_Success: "已完成",
    Localizations_Text_Identifier.Material_FilesUploader_Fail: "上傳失敗, 點擊 X 以查看更多資訊。",
    Localizations_Text_Identifier.Material_FilesUploader_Retry: "重新上傳",
    Localizations_Text_Identifier.Material_FilesUploader_FinishSubmission: "完成",
    Localizations_Text_Identifier.Material_FilesUploader_Inserting: "正在新增至資料庫...",
    Localizations_Text_Identifier.Material_FilesUploader_InsertSuccess: "章節組件內容及附件已成功新增至資料庫",
    Localizations_Text_Identifier.Material_FilesUploader_InsertFail: "新增至資料庫時發生錯誤，請重新嘗試",
    Localizations_Text_Identifier.Material_FilesUploader_LoadingServerResponse: "正在等待初始化上傳程序...",
    Localizations_Text_Identifier.Material_FilesUploader_ServerResponseSuccess: "上傳程序已初始化",
    Localizations_Text_Identifier.Course_View_Title: "我的課程",
    Localizations_Text_Identifier.Course_View_NoCourses: "現時未有任何課程",
    Localizations_Text_Identifier.Course_View_StatusFilter: "課程狀態篩選",
    Localizations_Text_Identifier.Course_View_DuplicateDetails: "複製課程資訊以新增課程",
    Localizations_Text_Identifier.StatusFilter_All:"所有",
    Localizations_Text_Identifier.StatusFilter_Expired:"已完結",
    Localizations_Text_Identifier.StatusFilter_Opening:"正在開放中",
    Localizations_Text_Identifier.StatusFilter_Coming:"即將開放",
    Localizations_Text_Identifier.Course_Page_Title: "課程章節",
    Localizations_Text_Identifier.Course_Page_UnitStatusFilter: "課程章節狀態篩選",
    Localizations_Text_Identifier.Course_View_LoadingList: "正在讀取\n課程...",
    Localizations_Text_Identifier.Course_Page_LoadingMaterialList:"正在讀取\n章節組件內容...",
    Localizations_Text_Identifier.Course_Page_ViewDescription: "課程簡介",
    Localizations_Text_Identifier.Course_Page_EditDetails: "修改課程資訊",
    Localizations_Text_Identifier.Course_Page_AddContent: "新增課程章節",
    Localizations_Text_Identifier.Course_Page_NoAnyContent: "現時並沒有任何內容",
    Localizations_Text_Identifier.Course_Page_Delete: "刪除此課程",
    Localizations_Text_Identifier.Course_Page_DeleteWarning: "你確定要永久刪除\n整個課程\n(包括此課程的所有章節內容及附件)嗎？\n\n一但確定，將不能復原!",
    Localizations_Text_Identifier.Course_Page_DeleteSuccess: "此課程及其所有章節內容和附件已成功刪除!",
    Localizations_Text_Identifier.Course_Page_CourseNotFound: "內容已無法讀取\n原因：上傳者已刪除有關內容",
    Localizations_Text_Identifier.Course_Page_CourseOutdated: "內容已無法讀取\n原因：課程的開放時限已過",
    Localizations_Text_Identifier.Course_Edit_LoadingData: "正在讀取\n課程資料中...",
    Localizations_Text_Identifier.Course_ContentPage_AppBarTitle: "章節組件內容",
    Localizations_Text_Identifier.Course_ContentPage_LoadingAttachmentList: "正在讀取\n章節組件資訊及附件中...",
    Localizations_Text_Identifier.Course_ContentPage_StatusFilter: "章節內容狀態篩選",
    Localizations_Text_Identifier.Course_ContentPage_Delete: "刪除此章節組件的內容及其所有附件",
    Localizations_Text_Identifier.Course_ContentPage_DeleteWarning: "你確定要永久刪除\n此章節組件的內容及其所有附件嗎？\n\n一但確定，將不能復原!",
    Localizations_Text_Identifier.Course_ContentPage_DeleteSuccess: "此章節組件的內容及其所有附件已成功刪除!",
    Localizations_Text_Identifier.Course_ContentPage_OpenFile: "開啟",
    Localizations_Text_Identifier.Course_ContentPage_DownloadFile: "下載",
    Localizations_Text_Identifier.Course_ContentPage_OpenWebsiteWarning_Title: "網絡流量警示",
    Localizations_Text_Identifier.Course_ContentPage_OpenWebsiteWarning: "請注意：你即將前往其他網站，\n而該網站可能附有影片或大量圖片，這將需要大量網絡流量。\n請盡量使用無限流量的Wifi瀏覽該網頁\n否則，你的電訊供應商將有機會收取你額外流動網絡費用。",
    Localizations_Text_Identifier.Course_ContentPage_NoAnyAttachment: "現時並沒有任何附件",
    Localizations_Text_Identifier.Course_ContentPage_ContentNotFound: "此章節組件的內容已無法讀取\n原因：上傳者或已刪除有關內容\n請點擊標題右方按鈕,\n以從伺服器內讀取最新內容",
    Localizations_Text_Identifier.Course_ContentPage_ContentOutdated: "此章節組件的內容已無法讀取\n原因：課程內容的開放時限已過\n請點擊標題右方按鈕,\n以從伺服器內讀取最新內容",
    Localizations_Text_Identifier.Course_ContentPage_AttachmentNotFound: "無法從伺服器內讀取此檔案\n原因：上傳者或已刪除有關附件\n請點擊標題右方按鈕,\n以從伺服器內讀取最新內容",
    Localizations_Text_Identifier.Course_ContentPage_MarkedasComplete: "標示為已完成",
    Localizations_Text_Identifier.Course_ContentPage_MarkedasNotComplete: "標示為未完成",
    Localizations_Text_Identifier.Course_ContentPage_EditDetails: "編輯內容詳情及附件",
    Localizations_Text_Identifier.Course_ContentPage_Editor_AppBarTitle: "編輯章節組件內容",
    Localizations_Text_Identifier.Course_ContentPage_Editor_LoadingData: "正在讀取\n章節組件內容詳情及附件",
    Localizations_Text_Identifier.ResetFormWarning:"你確定要清除所有已輸入欄位？",
    Localizations_Text_Identifier.CourseCreator_Creator_AppBarTitle:"新增課程",
    Localizations_Text_Identifier.CourseCreator_Creator_Title:"課程標題",
    Localizations_Text_Identifier.CourseCreator_Creator_Desc:"課程簡介",
    Localizations_Text_Identifier.CourseCreator_Creator_Groups:"獲授權存取的群組",
    Localizations_Text_Identifier.CourseCreator_Creator_GroupUsers:"\n所屬用戶列表",
    Localizations_Text_Identifier.CourseCreator_Creator_GroupUsers_NULL:"目前此群組並沒有任何用戶",
    Localizations_Text_Identifier.CourseCreator_Creator_StartTime:"課程開放時間",
    Localizations_Text_Identifier.CourseCreator_Creator_StartDate:"課程開放日期",
    Localizations_Text_Identifier.CourseCreator_Creator_EndTime:"課程完結時間",
    Localizations_Text_Identifier.CourseCreator_Creator_EndDate:"課程完結日期",
    Localizations_Text_Identifier.CourseCreator_Creator_AddNewGroup:"新增用戶群組",
    Localizations_Text_Identifier.CourseCreator_Preview_AppBarTitle: "預覽課程",
    Localizations_Text_Identifier.CourseCreator_Preview_StartDateTime:"課程開放時期",
    Localizations_Text_Identifier.CourseCreator_Preview_EndDateTime:"課程完結時期",
    Localizations_Text_Identifier.CourseCreator_InsertSuccess:"課程已新增至資料庫",
    Localizations_Text_Identifier.CourseCreator_Editor_AppBarTitle: "編輯課程資訊",
    Localizations_Text_Identifier.EditingPreview_AppBarTitle: "預覽修改",
    Localizations_Text_Identifier.Editing_Confirm: "確定修改",
    Localizations_Text_Identifier.CourseCreator_EditingSuccess: "課程資料已成功更新至資料庫",
    Localizations_Text_Identifier.CourseCreator_EditingFail: "發生未知錯誤，\n課程資料未能新增或更新至資料庫，\n請重新嘗試。",
    Localizations_Text_Identifier.DownloadFile_FileExists_Msg_Opening: "系統檢測到檔案\n[",
    Localizations_Text_Identifier.DownloadFile_FileExists_Msg_Ending: "]\n已存在，\n\n你確定要重新下載並覆寫此檔案嗎？",
    Localizations_Text_Identifier.DownloadFile_FileRedownload: "重新下載",
    Localizations_Text_Identifier.DownloadFile_Success:"已完成下載\n\n檔案已儲存至\n「下載」資料夾內。",
    Localizations_Text_Identifier.DownloadFile_Fail:"下載過程中發生錯誤\n請先檢查你的網絡連接\n然後嘗試重新下載。",
    Localizations_Text_Identifier.DownloadFile_WaitForServerResponse:"正等待伺服器回應...",
    Localizations_Text_Identifier.DownloadFile_WaitForDownloadProcess: "正在等待\n初始化下載程序",
    Localizations_Text_Identifier.DownloadFile_FileDownloading:"\n檔案下載中...",
    Localizations_Text_Identifier.SendEmail: "聯絡研究團隊",
    Localizations_Text_Identifier.CourseUnitListPage_LoadingList: "正在讀取\n課程章節...",
    Localizations_Text_Identifier.CourseUnitPage_AppBarTitle: "課程",
    Localizations_Text_Identifier.CourseUnitPage_Delete: "刪除此課程章節",
    Localizations_Text_Identifier.CourseUnitPage_DeleteWarning: "你確定要永久刪除\n整個章節(包括章節內的所有組件及其所有附件)嗎？\n\n一但確定，將不能復原!",
    Localizations_Text_Identifier.CourseUnitPage_DeleteSuccess: "此章節已成功刪除!",
    Localizations_Text_Identifier.CourseUnitPage_EditDetails: "修改章節資訊",
    Localizations_Text_Identifier.CourseUnitPage_DuplicateDetails: "複製章節資訊以新增章節",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_AppBarTitle: "新增章節",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_Title: "章節標題",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_Desc: "章節簡介",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_StartTime: "章節開放時間",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_StartDate: "章節開放日期",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_EndTime: "章節完結時間",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_EndDate: "章節完結日期",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_SkipModuleSelection_Checkbox: "跳過組件選擇頁面",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_SkipModuleSelection_Default: "預設 (首個章節組件)",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_SkipModuleSelection: "導向至",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_SkipModuleSelection_Desc: "預設將會自動導向至首個章節組件\n如需更改，請在列表中選擇跳過組件選擇頁面後的導向組件\n若此章節並無任何組件，將不會跳過組件選擇頁面。",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_SkipModuleSelection_Checkbox_Desc: "開啟此功能將會強制跳過組件選擇頁面\n並自動導向指定組件\n此功能只會對一般用戶有效，\n管理員仍然會進入組件選擇頁面\n\n請於下方「導向至」選擇指定導向的組件",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_InsertSuccess: "課程章節已成功新增至資料庫",
    Localizations_Text_Identifier.CourseUnitCreator_Editor_AppBarTitle: "編輯章節資訊",
    Localizations_Text_Identifier.CourseUnitCreator_Creator_EditingSuccess: "課程章節已成功更新至資料庫",
    Localizations_Text_Identifier.CourseUnitCreator_Preview_StartDateTime: "章節開放時期",
    Localizations_Text_Identifier.CourseUnitCreator_Preview_EndDateTime: "章節完結時期",
    Localizations_Text_Identifier.CourseUnitCreator_EditingFail: "發生未知錯誤，\n章節資料未能新增或更新至資料庫，\n請重新嘗試。",
    Localizations_Text_Identifier.CourseUnit_Page_ViewDescription: "章節簡介",
    Localizations_Text_Identifier.UnitModule_Page_ViewDescription: "章節組件簡介",
    Localizations_Text_Identifier.CourseUnitListPage_UnitSelectionTitle: "課程章節",
    Localizations_Text_Identifier.CourseUnitPage_ModuleSelectionTitle: "章節組件選擇",
    Localizations_Text_Identifier.ModulePage_AttachmentSelectionTitle: "章節組件附件",
    Localizations_Text_Identifier.Survey_AppBarTitle: "我的問卷",
    Localizations_Text_Identifier.Survey_Editor_Edit_AppBarTitle:"修改問卷",
    Localizations_Text_Identifier.Survey_Editor_Create_AppBarTitle:"新增問卷",
    Localizations_Text_Identifier.Survey_Editor_Title:"問卷標題",
    Localizations_Text_Identifier.Survey_Editor_Desc:"問卷簡介",
    Localizations_Text_Identifier.Survey_Editor_Link:"問卷參考連結",
    Localizations_Text_Identifier.Survey_Editor_LinkDesc: "請輸入Google Form已預填回應的鏈結\n(可參考用戶操作說明)",
    Localizations_Text_Identifier.Survey_Editor_StartDate:"問卷開放日期",
    Localizations_Text_Identifier.Survey_Editor_StartTime:"問卷開放時間",
    Localizations_Text_Identifier.Survey_Editor_EndDate:"問卷完結日期",
    Localizations_Text_Identifier.Survey_Editor_EndTime:"問卷完結時間",
    Localizations_Text_Identifier.Survey_Editor_Preview_StartDateTime:"問卷開放時期",
    Localizations_Text_Identifier.Survey_Editor_Preview_EndDateTime:"問卷完結時期",
    Localizations_Text_Identifier.Survey_Editor_Creator_InsertSuccess: "問卷已成功新增至資料庫",
    Localizations_Text_Identifier.Survey_Editor_Creator_UpdateSuccess: "問卷已成功更新",
    Localizations_Text_Identifier.Survey_Editor_Creator_Fail: "發生未知錯誤，\n問卷資料未能新增或更新至資料庫，\n請重新嘗試。",
    Localizations_Text_Identifier.Survey_Editor_LoadingSurveyData: "正在讀取\n問卷資料",
    Localizations_Text_Identifier.Survey_ListPage_AppBarTitle: "問卷列表",
    Localizations_Text_Identifier.Survey_ListPage_NoSurvey: "現時並沒有任何問卷",
    Localizations_Text_Identifier.Survey_ListPage_LoadingList: "正在讀取\n問卷",
    Localizations_Text_Identifier.Survey_ListPage_StatusFilter: "問卷狀態篩選",
    Localizations_Text_Identifier.Survey_ListPage_ViewSurvey: "查看問卷",
    Localizations_Text_Identifier.Survey_ListPage_DeleteSurvey: "刪除此問卷",
    Localizations_Text_Identifier.Survey_ListPage_DeleteSurvey_Warning_Opening: "你確定要永久刪除問卷\n[",
    Localizations_Text_Identifier.Survey_ListPage_DeleteSurvey_Warning_Ending: "]？\n\n一但確定，將不能復原!",
    Localizations_Text_Identifier.Survey_ListPage_DeleteSurvey_Success: "\n問卷已成功刪除!",
    Localizations_Text_Identifier.Survey_ListPage_DuplicateDetails: "複製問卷資訊以新增問卷",
    Localizations_Text_Identifier.Course_View_ViewCourse: "查看課程",
    Localizations_Text_Identifier.CourseUnitListPage_ViewUnit: "查看課程章節",
    Localizations_Text_Identifier.CourseUnitPage_ViewModule: "查看章節組件",
    Localizations_Text_Identifier.Progress_Module_AttToal_Title: "章節組件進度",
    Localizations_Text_Identifier.Progress_Unit_AttTotal_Title: "章節總進度",
    Localizations_Text_Identifier.Progress_Unit_ModuleTotal_Title: "章節組件完成度",
    Localizations_Text_Identifier.Progress_Course_AttTotal_Title: "課程總進度",
    Localizations_Text_Identifier.Progress_Course_UnitTotal_Title: "課程章節完成度",
    Localizations_Text_Identifier.Progress_Course_ModuleTotal_Title: "課程章節組件完成度",
    Localizations_Text_Identifier.Progress_Updating: "正在讀取及更新您的課程進度...",
    Localizations_Text_Identifier.Profiles_ViewCourseProgress_title: "查看所有課程",
    Localizations_Text_Identifier.Profiles_ViewCourseProgress_Desc: "查看課程內容，\n並隨時檢視進度",
    Localizations_Text_Identifier.Profiles_ViewSurvey_title: "查看所有問卷",
    Localizations_Text_Identifier.Profiles_ViewSurvey_Desc: "查看及回答問卷",
    Localizations_Text_Identifier.Profiles_ChangePassword_title: "更改密碼",
    Localizations_Text_Identifier.Profiles_ChangePassword_Desc: "更改用以登入此帳號的密碼",
    Localizations_Text_Identifier.Profiles_ChangePassword_DoubleCheck: "再次輸入密碼",
    Localizations_Text_Identifier.Profiles_ChangePassword_DoubleCheck_Failed: "輸入的密碼不一致，請重新輸入。",
    Localizations_Text_Identifier.Profiles_ChangePassword_Condition_Length: "\n長度必須至少為 9 個字符",
    Localizations_Text_Identifier.Profiles_ChangePassword_Condition_ContainUpper: "\n必須包含至少 1 個大寫英文字母",
    Localizations_Text_Identifier.Profiles_ChangePassword_Condition_ContainLower: "\n必須包含至少 1 個小寫英文字母",
    Localizations_Text_Identifier.Profiles_ChangePassword_Condition_SpecialCharacter: "\n必須包含至少 1 個以下列明的特殊字符\n* ! # @ &",
    Localizations_Text_Identifier.Profiles_ChangePassword_Success: "密碼已更改\n請以新密碼重新登入此帳號。",
    Localizations_Text_Identifier.Profiles_ChangePassword_Failed: "密碼更改時出現未知錯誤，請重新嘗試。",
    Localizations_Text_Identifier.Profiles_ChangePassword_Condition_Check_TopMsg: "密碼不符合以下條件，請重新輸入",
    Localizations_Text_Identifier.Profiles_ChangeDefaultEmail_title: "更改電郵地址",
    Localizations_Text_Identifier.Profiles_ChangeDefaultEmail_InBoxDesc: "請於下方輸入新的電郵地址\n如您使用電郵登入帳號\n請於更改後使用新的電郵登入帳號\n\n請注意：更改電郵地址須重新驗證，你必須確保該電郵能正常收取郵件，否則你將無法完成驗證程序",
    Localizations_Text_Identifier.Profiles_ChangeDefaultEmail_Desc: "更改此帳號的預設電郵地址",
    Localizations_Text_Identifier.Profiles_ChangeDefaultEmail_FormatError: "您所輸入的電郵地址格式錯誤\n請重新輸入\n\n電郵地址格式應如:\nname@example.com",
    Localizations_Text_Identifier.Profiles_ChangeDefaultEmail_Success: "預設電郵地址已更改\n請重新登入\n\n如您使用電郵登入帳號\n請使用更改後的電郵登入帳號\n\n此外系統已發送驗證郵件至你所更改的電子郵箱\n你必須完成驗證才可登入\n郵件或有可能被電子郵件服務供應商列為垃圾郵件，\n若您未能在收件箱找到由 auto@sme.dsgshk.com 所發出的郵件，\n請檢查您的垃圾郵件。",
    Localizations_Text_Identifier.Profiles_ChangeDefaultEmail_Exists: "此電子郵件地址已被使用\n請嘗試使用其他電子郵件地址",
    Localizations_Text_Identifier.Profiles_ChangeDefaultEmail_Failed: "電郵地址更改時出現未知錯誤，請重新嘗試。",
    Localizations_Text_Identifier.SendResetPWRequest_BtnTitle: "忘記密碼？",
    Localizations_Text_Identifier.SendResetPWRequest_Title: "申請重置密碼",
    Localizations_Text_Identifier.SendResetPWRequest_Desc: "如您忘記帳號密碼\n請於下方輸入您的帳號或電郵\n系統將會發送重置密碼確認信至您註冊帳號時所使用的電郵。",
    Localizations_Text_Identifier.SendResetPWRequest_Success: "重置密碼確認信\n已發送至您註冊帳號時所使用的電郵",
    Localizations_Text_Identifier.SendResetPWRequest_Failed: "申請時發生未知錯誤，請再次嘗試。",
    Localizations_Text_Identifier.SendResetPWRequest_ACNotFound: "系統未能找到此帳號或電郵地址 /\n該電郵地址與帳號的記錄不相符，\n請重新輸入。",
    Localizations_Text_Identifier.SendResetPWRequest_ApplicationInvaild: "應用程式驗證失敗\n請更新應用程式至最新版本或重新下載。",
    Localizations_Text_Identifier.SendResetPWRequest_Sending: "系統正在處理您的申請",
    Localizations_Text_Identifier.SendValidationRequest_Failed:"帳號已存在\n但系統基於連接問題\n未能順利發出驗證電郵\n請重新嘗試。\n\n如你在註冊時出現此問題\n請返回登入頁面\n嘗試登入你的帳號，以獲取驗證郵件。",
    Localizations_Text_Identifier.Profiles_NotificationManager_title: "提醒管理員",
    Localizations_Text_Identifier.Profiles_NotificationManager_Insidetitle: "提醒",
    Localizations_Text_Identifier.Profiles_NotificationManager_Desc: "檢視或刪除\n已設定的課程通知及提醒",
    Localizations_Text_Identifier.Profiles_NotificationManager_ViewNotificationDesc: "通知內容",
    Localizations_Text_Identifier.Profiles_NotificationManager_Delete: "刪除此提醒",
    Localizations_Text_Identifier.Profiles_NotificationManager_DeleteWarning: "你確定要刪除此提醒嗎？",
    Localizations_Text_Identifier.Profiles_NotificationManager_DeleteSuccess: "\n此提醒已成功刪除",
    Localizations_Text_Identifier.Profiles_UserGroupSetting_title: "用戶群組管理",
    Localizations_Text_Identifier.Profiles_UserGroupSetting_Desc: "檢視、新增或刪除\n用戶群組及成員名單",
    Localizations_Text_Identifier.Profiles_UserGroupSetting_ViewUsers: "檢視用戶名單",
    Localizations_Text_Identifier.Profiles_UserGroupSetting_Delete: "刪除此用戶群組",
    Localizations_Text_Identifier.Profiles_UserGroupSetting_DeleteWarning: "你確定要刪除以下群組嗎？\n",
    Localizations_Text_Identifier.Profiles_UserGroupSetting_DeleteSuccess: "以下群組已成功刪除\n",
    Localizations_Text_Identifier.Profiles_SubGroup_Prefix: "已加入的群組：",
    Localizations_Text_Identifier.Profiles_SubGroup_NoGroup: "您沒有加入任何群組",
    Localizations_Text_Identifier.NotificationManager_AddCourseReminder: "設定課程提醒",
    Localizations_Text_Identifier.NotificationManager_SettingCourseReminder_TimeTitle: "設定每日提醒時間",
    Localizations_Text_Identifier.NotificationManager_CourseReminderTitle: "每日課程提醒 - ",
    Localizations_Text_Identifier.NotificationManager_CourseReminderContentOpening: "請緊記登入你的帳戶，\n並繼續參與及瀏覽課程內容！",
    Localizations_Text_Identifier.NotificationManager_CourseReminderContentEnding: "",
    Localizations_Text_Identifier.NotificationManager_AddLoginReminder: "新增登入提醒",
    Localizations_Text_Identifier.NotificationManager_ReminderAdded: "\n已成功新增上述課程的提醒",
    Localizations_Text_Identifier.NotificationManager_SettingCourseReminder_TimeFieldNull: "請先設定每日提醒時間",
    Localizations_Text_Identifier.Profiles_NotificationManager_TimeTitle_Opening: "將於每日 ",
    Localizations_Text_Identifier.Profiles_NotificationManager_TimeTitle_Ending: " 顯示上述課程的提醒",
    Localizations_Text_Identifier.GroupUser_GettingUsersList: "正在讀取用戶列表...",
    Localizations_Text_Identifier.GroupUser_Setting: "設定此用戶群組的名單",
    Localizations_Text_Identifier.GroupUser_ListTitle_Start: "設定\n",
    Localizations_Text_Identifier.GroupUser_ListTitle_End: "\n的用戶名單",
    Localizations_Text_Identifier.GroupUser_ListButton: "按此設定以上群組的用戶名單",
    Localizations_Text_Identifier.GroupUser_SettingTitle_Start: "當前設定:\n",
    Localizations_Text_Identifier.GroupUser_Setting_UploadingToDB: "正在更新用戶名單...",
    Localizations_Text_Identifier.GroupUser_Setting_Upload_Failed: "更新失敗，請再次嘗試",
    Localizations_Text_Identifier.GroupUser_Setting_Upload_Success: "名單已經成功更新至資料庫。",
    Localizations_Text_Identifier.GroupUser_Setting_Upload_NameExits: "此群組已存在，\n請更改為另一名稱",
    Localizations_Text_Identifier.GroupUser_Setting_Upload_NameNull: "群組名稱不可為空值，\n請先輸入群組名稱",
    Localizations_Text_Identifier.GroupUser_List_UsersCount_Title: "群組成員人數: ",
    Localizations_Text_Identifier.Contact_Form_Lable_Title: "主旨",
    Localizations_Text_Identifier.Contact_Form_Lable_Desc: "電郵內容",
    Localizations_Text_Identifier.Contact_Form_Lable_ReplyEmail: "收取回郵的電郵地址",
    Localizations_Text_Identifier.Contact_Form_Lable_ReplyEmail_Desc: "系統已預設為您註冊所使用的電郵\n如您想以其他電郵收取回覆，請更改此電郵地址",
    Localizations_Text_Identifier.Contact_Form_Lable_NameTitle: "稱謂",
    Localizations_Text_Identifier.Contact_Form_Lable_Preview: "預覽電郵",
    Localizations_Text_Identifier.Contact_Form_Lable_Send: "傳送電郵",
    Localizations_Text_Identifier.Contact_Form_Lable_NameTitle_Mr: "先生",
    Localizations_Text_Identifier.Contact_Form_Lable_NameTitle_Mrs: "女士",
    Localizations_Text_Identifier.Contact_Form_Lable_NameTitle_Ms: "小姐",
    Localizations_Text_Identifier.Contact_Form_Lable_NameTitle_Miss: "小姐",
    Localizations_Text_Identifier.Contact_Form_Lable_NameTitle_Dr: "博士",
    Localizations_Text_Identifier.Contact_Form_Sending:"正在傳送聯絡電郵...",
    Localizations_Text_Identifier.Contact_Form_Sent_Success: "感謝您的查詢，\n電郵已成功傳送，請耐心等待研究團隊的回覆\n\n電郵副本已發送至您的電郵以作備存。",
    Localizations_Text_Identifier.Contact_Form_Sent_Failed: "電郵未能成功發出，請重新嘗試。\n\n若仍未能發出，請截取本畫面作為附件，然後聯絡技術人員。",
    Localizations_Text_Identifier.Contact_Form_Sent_OverLimit: "基於我們的公平使用政策(FUP)，\n每位用戶每日只可發送最多 10 次查詢。\n\n你已發送的查詢已超出上限\n因此電郵未能成功發出，\n請於明天再重新嘗試。\n",
    Localizations_Text_Identifier.TechSupport_Label_Title: "技術支援",
    Localizations_Text_Identifier.TechSupport_Label_Desc: "向技術人員回報\n有關伺服器、程式等錯誤訊息或問題\n以便獲得進一步的支援",
    Localizations_Text_Identifier.TechSupport_DefaultTitle: "請在此簡單描述技術問題",
    Localizations_Text_Identifier.TechSupport_Question_Title: "請在此部分詳細說明技術問題",
    Localizations_Text_Identifier.TechSupport_Attachment_Title: "如有圖片可協助說明以上技術問題，請將有關圖片加入至附件。",
    Localizations_Text_Identifier.TechSupport_Label_UserDeviceInformation: "裝置資訊：\n",
    Localizations_Text_Identifier.TechSupport_Label_UserDeviceModel: "裝置型號: ",
    Localizations_Text_Identifier.TechSupport_Label_UserDeviceVersion: "裝置操作系統版本: ",
    Localizations_Text_Identifier.TechSupport_Label_Manufacturer: "裝置生產商: ",
    Localizations_Text_Identifier.ResendValidationEmailButtonTitle: "重新發送驗證郵件",
    Localizations_Text_Identifier.ResendValidationEmail_Success: "系統已重新發送驗證郵件至你的電子郵箱\n郵件或有可能被電子郵件服務供應商列為垃圾郵件，\n若您未能在收件箱找到由 auto@sme.dsgshk.com 所發出的郵件，\n請檢查您的垃圾郵件。",
    Localizations_Text_Identifier.ResendValidationEmail_Sending: "系統正在處理您的請求，請稍等",
  }
};

final List<String> GenderList =
  [
    Localizations_Text[Localizations_Language_Identifier.Language_Eng][Localizations_Text_Identifier.Text_male],
    Localizations_Text[Localizations_Language_Identifier.Language_Eng][Localizations_Text_Identifier.Text_Female],
    Localizations_Text[Localizations_Language_Identifier.Language_Eng][Localizations_Text_Identifier.Text_Other]
  ];
final List<String> GenderList_TC =
  [
    Localizations_Text[Localizations_Language_Identifier.Language_TC][Localizations_Text_Identifier.Text_male],
    Localizations_Text[Localizations_Language_Identifier.Language_TC][Localizations_Text_Identifier.Text_Female],
    Localizations_Text[Localizations_Language_Identifier.Language_TC][Localizations_Text_Identifier.Text_Other]
  ];

final List<String> Course_Filter =
[
  Localizations_Text[Localizations_Language_Identifier.Language_Eng][Localizations_Text_Identifier.StatusFilter_All],
  Localizations_Text[Localizations_Language_Identifier.Language_Eng][Localizations_Text_Identifier.StatusFilter_Opening],
  Localizations_Text[Localizations_Language_Identifier.Language_Eng][Localizations_Text_Identifier.StatusFilter_Coming],
  Localizations_Text[Localizations_Language_Identifier.Language_Eng][Localizations_Text_Identifier.StatusFilter_Expired],
];

final List<String> Course_Filter_TC =
[
  Localizations_Text[Localizations_Language_Identifier.Language_TC][Localizations_Text_Identifier.StatusFilter_All],
  Localizations_Text[Localizations_Language_Identifier.Language_TC][Localizations_Text_Identifier.StatusFilter_Opening],
  Localizations_Text[Localizations_Language_Identifier.Language_TC][Localizations_Text_Identifier.StatusFilter_Coming],
  Localizations_Text[Localizations_Language_Identifier.Language_TC][Localizations_Text_Identifier.StatusFilter_Expired],
];

final List<String> NameTitle =
[
  Localizations_Text[Localizations_Language_Identifier.Language_Eng][Localizations_Text_Identifier.Contact_Form_Lable_NameTitle_Mr],
  Localizations_Text[Localizations_Language_Identifier.Language_Eng][Localizations_Text_Identifier.Contact_Form_Lable_NameTitle_Mrs],
  Localizations_Text[Localizations_Language_Identifier.Language_Eng][Localizations_Text_Identifier.Contact_Form_Lable_NameTitle_Ms],
  Localizations_Text[Localizations_Language_Identifier.Language_Eng][Localizations_Text_Identifier.Contact_Form_Lable_NameTitle_Miss],
  Localizations_Text[Localizations_Language_Identifier.Language_Eng][Localizations_Text_Identifier.Contact_Form_Lable_NameTitle_Dr],
];

final List<String> NameTitle_TC =
[
  Localizations_Text[Localizations_Language_Identifier.Language_TC][Localizations_Text_Identifier.Contact_Form_Lable_NameTitle_Mr],
  Localizations_Text[Localizations_Language_Identifier.Language_TC][Localizations_Text_Identifier.Contact_Form_Lable_NameTitle_Mrs],
  Localizations_Text[Localizations_Language_Identifier.Language_TC][Localizations_Text_Identifier.Contact_Form_Lable_NameTitle_Ms],
  Localizations_Text[Localizations_Language_Identifier.Language_TC][Localizations_Text_Identifier.Contact_Form_Lable_NameTitle_Miss],
  Localizations_Text[Localizations_Language_Identifier.Language_TC][Localizations_Text_Identifier.Contact_Form_Lable_NameTitle_Dr],
];